<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>New statistics for the design researcher</title>
  <meta name="description" content="A statistics book for designers, human factors specialists, UX researchers, applied psychologists and everyone else who works hard to make this world a better place.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="New statistics for the design researcher" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A statistics book for designers, human factors specialists, UX researchers, applied psychologists and everyone else who works hard to make this world a better place." />
  <meta name="github-repo" content="schmettow/New_Stats" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="New statistics for the design researcher" />
  
  <meta name="twitter:description" content="A statistics book for designers, human factors specialists, UX researchers, applied psychologists and everyone else who works hard to make this world a better place." />
  

<meta name="author" content="Martin Schmettow">


<meta name="date" content="2018-11-20">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="linear-models.html">
<link rel="next" href="GLM.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="part"><span><b>I Preparations</b></span></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#whom-this-book-is-for"><i class="fa fa-check"></i><b>1.1</b> Whom this book is for</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#the-empirical-design-researcher"><i class="fa fa-check"></i><b>1.1.1</b> The empirical design researcher</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#the-experimentalist"><i class="fa fa-check"></i><b>1.1.2</b> The experimentalist</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#the-applied-researcher"><i class="fa fa-check"></i><b>1.1.3</b> The applied researcher</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#assumptions"><i class="fa fa-check"></i><b>1.2</b> Assumptions</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#how-to-read-this-book"><i class="fa fa-check"></i><b>1.3</b> How to read this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="design-research.html"><a href="design-research.html"><i class="fa fa-check"></i><b>2</b> Elements of quantitative design research</a><ul>
<li class="chapter" data-level="2.1" data-path="design-research.html"><a href="design-research.html#studies"><i class="fa fa-check"></i><b>2.1</b> Studies</a></li>
<li class="chapter" data-level="2.2" data-path="design-research.html"><a href="design-research.html#observations-and-measurestbc"><i class="fa fa-check"></i><b>2.2</b> Observations and measures[TBC]</a><ul>
<li class="chapter" data-level="2.2.1" data-path="design-research.html"><a href="design-research.html#interaction-sequences"><i class="fa fa-check"></i><b>2.2.1</b> Interaction sequences</a></li>
<li class="chapter" data-level="2.2.2" data-path="design-research.html"><a href="design-research.html#performance-measures"><i class="fa fa-check"></i><b>2.2.2</b> performance measures</a></li>
<li class="chapter" data-level="2.2.3" data-path="design-research.html"><a href="design-research.html#experience-tbd"><i class="fa fa-check"></i><b>2.2.3</b> experience [TBD]</a></li>
<li class="chapter" data-level="2.2.4" data-path="design-research.html"><a href="design-research.html#design-features-tbd"><i class="fa fa-check"></i><b>2.2.4</b> design features [TBD]</a></li>
<li class="chapter" data-level="2.2.5" data-path="design-research.html"><a href="design-research.html#the-human-factor-tbd"><i class="fa fa-check"></i><b>2.2.5</b> the human factor [TBD]</a></li>
<li class="chapter" data-level="2.2.6" data-path="design-research.html"><a href="design-research.html#situations-tbd"><i class="fa fa-check"></i><b>2.2.6</b> situations [TBD]</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="design-research.html"><a href="design-research.html#decision_making"><i class="fa fa-check"></i><b>2.3</b> Decision making under uncertainty</a><ul>
<li class="chapter" data-level="2.3.1" data-path="design-research.html"><a href="design-research.html#measuring-uncertainty"><i class="fa fa-check"></i><b>2.3.1</b> Measuring uncertainty</a></li>
<li class="chapter" data-level="2.3.2" data-path="design-research.html"><a href="design-research.html#betting-on-designs"><i class="fa fa-check"></i><b>2.3.2</b> Betting on designs</a></li>
<li class="chapter" data-level="2.3.3" data-path="design-research.html"><a href="design-research.html#case-e-commerce-ab"><i class="fa fa-check"></i><b>2.3.3</b> Case: e-commerce A/B</a></li>
<li class="chapter" data-level="2.3.4" data-path="design-research.html"><a href="design-research.html#case99"><i class="fa fa-check"></i><b>2.3.4</b> Case: 99 seconds</a></li>
<li class="chapter" data-level="2.3.5" data-path="design-research.html"><a href="design-research.html#prior-information"><i class="fa fa-check"></i><b>2.3.5</b> Prior information</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html"><i class="fa fa-check"></i><b>3</b> Elements of Bayesian statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.1</b> Descriptive statistics</a><ul>
<li class="chapter" data-level="3.1.1" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#frequencies"><i class="fa fa-check"></i><b>3.1.1</b> Frequencies</a></li>
<li class="chapter" data-level="3.1.2" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#central-tendency"><i class="fa fa-check"></i><b>3.1.2</b> Central tendency</a></li>
<li class="chapter" data-level="3.1.3" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#dispersion"><i class="fa fa-check"></i><b>3.1.3</b> Dispersion</a></li>
<li class="chapter" data-level="3.1.4" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#associations"><i class="fa fa-check"></i><b>3.1.4</b> Associations</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#bayesian-inferential-statistics"><i class="fa fa-check"></i><b>3.2</b> Bayesian Inferential statistics</a></li>
<li class="chapter" data-level="3.3" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#bayesian-probability-theory"><i class="fa fa-check"></i><b>3.3</b> Bayesian probability theory</a><ul>
<li class="chapter" data-level="3.3.1" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#some-set-theory"><i class="fa fa-check"></i><b>3.3.1</b> Some set theory</a></li>
<li class="chapter" data-level="3.3.2" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#probability"><i class="fa fa-check"></i><b>3.3.2</b> Probability</a></li>
<li class="chapter" data-level="3.3.3" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#certainty-as-probability"><i class="fa fa-check"></i><b>3.3.3</b> Certainty as probability</a></li>
<li class="chapter" data-level="3.3.4" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#bayes-theorem"><i class="fa fa-check"></i><b>3.3.4</b> Bayes theorem</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#statistical-models"><i class="fa fa-check"></i><b>3.4</b> Statistical models</a><ul>
<li class="chapter" data-level="3.4.1" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#predictions-and-likelihood"><i class="fa fa-check"></i><b>3.4.1</b> Predictions and likelihood</a></li>
<li class="chapter" data-level="3.4.2" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#distributions"><i class="fa fa-check"></i><b>3.4.2</b> Distributions: patterns of randomness</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#bayesian-estimation"><i class="fa fa-check"></i><b>3.5</b> Bayesian estimation</a></li>
<li class="chapter" data-level="3.6" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html#what-is-wrong-with-classic-statistics-tbc"><i class="fa fa-check"></i><b>3.6</b> What is wrong with classic statistics? [TBC]</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="getting-started-r.html"><a href="getting-started-r.html"><i class="fa fa-check"></i><b>4</b> Getting started with R</a><ul>
<li class="chapter" data-level="4.1" data-path="getting-started-r.html"><a href="getting-started-r.html#setting-up-the-r-environment"><i class="fa fa-check"></i><b>4.1</b> Setting up the R environment</a><ul>
<li class="chapter" data-level="4.1.1" data-path="getting-started-r.html"><a href="getting-started-r.html#installing-cran-packages"><i class="fa fa-check"></i><b>4.1.1</b> Installing CRAN packages</a></li>
<li class="chapter" data-level="4.1.2" data-path="getting-started-r.html"><a href="getting-started-r.html#installing-packages-from-github"><i class="fa fa-check"></i><b>4.1.2</b> Installing packages from Github</a></li>
<li class="chapter" data-level="4.1.3" data-path="getting-started-r.html"><a href="getting-started-r.html#first_program"><i class="fa fa-check"></i><b>4.1.3</b> A first statistical program</a></li>
<li class="chapter" data-level="4.1.4" data-path="getting-started-r.html"><a href="getting-started-r.html#bibliographic-notes"><i class="fa fa-check"></i><b>4.1.4</b> Bibliographic notes</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="getting-started-r.html"><a href="getting-started-r.html#learning-r-a-primer"><i class="fa fa-check"></i><b>4.2</b> Learning R: a primer</a><ul>
<li class="chapter" data-level="4.2.1" data-path="getting-started-r.html"><a href="getting-started-r.html#assigning-and-calling-objects"><i class="fa fa-check"></i><b>4.2.1</b> Assigning and calling Objects</a></li>
<li class="chapter" data-level="4.2.2" data-path="getting-started-r.html"><a href="getting-started-r.html#vectors"><i class="fa fa-check"></i><b>4.2.2</b> Vectors</a></li>
<li class="chapter" data-level="4.2.3" data-path="getting-started-r.html"><a href="getting-started-r.html#basic-object-types"><i class="fa fa-check"></i><b>4.2.3</b> Basic object types</a></li>
<li class="chapter" data-level="4.2.4" data-path="getting-started-r.html"><a href="getting-started-r.html#operators-and-functions"><i class="fa fa-check"></i><b>4.2.4</b> Operators and functions</a></li>
<li class="chapter" data-level="4.2.5" data-path="getting-started-r.html"><a href="getting-started-r.html#storing-data-in-data-frames"><i class="fa fa-check"></i><b>4.2.5</b> Storing data in data frames</a></li>
<li class="chapter" data-level="4.2.6" data-path="getting-started-r.html"><a href="getting-started-r.html#import-export-and-archiving"><i class="fa fa-check"></i><b>4.2.6</b> Import, export and archiving</a></li>
<li class="chapter" data-level="4.2.7" data-path="getting-started-r.html"><a href="getting-started-r.html#case-environments"><i class="fa fa-check"></i><b>4.2.7</b> Case environments</a></li>
<li class="chapter" data-level="4.2.8" data-path="getting-started-r.html"><a href="getting-started-r.html#structuring-data"><i class="fa fa-check"></i><b>4.2.8</b> Structuring data</a></li>
<li class="chapter" data-level="4.2.9" data-path="getting-started-r.html"><a href="getting-started-r.html#data-transformation"><i class="fa fa-check"></i><b>4.2.9</b> Data transformation</a></li>
<li class="chapter" data-level="4.2.10" data-path="getting-started-r.html"><a href="getting-started-r.html#plotting-data"><i class="fa fa-check"></i><b>4.2.10</b> Plotting data</a></li>
<li class="chapter" data-level="4.2.11" data-path="getting-started-r.html"><a href="getting-started-r.html#fitting-regression-models"><i class="fa fa-check"></i><b>4.2.11</b> Fitting regression models</a></li>
<li class="chapter" data-level="4.2.12" data-path="getting-started-r.html"><a href="getting-started-r.html#knitting-statistical-reports"><i class="fa fa-check"></i><b>4.2.12</b> Knitting statistical reports</a></li>
<li class="chapter" data-level="4.2.13" data-path="getting-started-r.html"><a href="getting-started-r.html#exercises-1"><i class="fa fa-check"></i><b>4.2.13</b> Exercises</a></li>
<li class="chapter" data-level="4.2.14" data-path="getting-started-r.html"><a href="getting-started-r.html#bibliographic-notes-1"><i class="fa fa-check"></i><b>4.2.14</b> Bibliographic notes</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Models</b></span></li>
<li class="chapter" data-level="5" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>5</b> Linear models</a><ul>
<li class="chapter" data-level="5.1" data-path="linear-models.html"><a href="linear-models.html#quantification-at-work-grand-mean-models"><i class="fa fa-check"></i><b>5.1</b> Quantification at work: grand mean models</a><ul>
<li class="chapter" data-level="5.1.1" data-path="linear-models.html"><a href="linear-models.html#reading-coefficient-tables"><i class="fa fa-check"></i><b>5.1.1</b> Reading coefficient tables</a></li>
<li class="chapter" data-level="5.1.2" data-path="linear-models.html"><a href="linear-models.html#likelihood-and-random-term"><i class="fa fa-check"></i><b>5.1.2</b> Likelihood and random term</a></li>
<li class="chapter" data-level="5.1.3" data-path="linear-models.html"><a href="linear-models.html#random_walk"><i class="fa fa-check"></i><b>5.1.3</b> Do the random walk: Markov Chain Monte Carlo sampling</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="linear-models.html"><a href="linear-models.html#linear-regression"><i class="fa fa-check"></i><b>5.2</b> Walk the line: linear regression</a><ul>
<li class="chapter" data-level="5.2.1" data-path="linear-models.html"><a href="linear-models.html#transforming-variables"><i class="fa fa-check"></i><b>5.2.1</b> Transforming variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="linear-models.html"><a href="linear-models.html#correlations"><i class="fa fa-check"></i><b>5.2.2</b> Correlations</a></li>
<li class="chapter" data-level="5.2.3" data-path="linear-models.html"><a href="linear-models.html#endlessly-linear"><i class="fa fa-check"></i><b>5.2.3</b> Endlessly linear</a></li>
<li class="chapter" data-level="5.2.4" data-path="linear-models.html"><a href="linear-models.html#posterior-predictions"><i class="fa fa-check"></i><b>5.2.4</b> Posterior predictions</a></li>
<li class="chapter" data-level="5.2.5" data-path="linear-models.html"><a href="linear-models.html#exercises-2"><i class="fa fa-check"></i><b>5.2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="linear-models.html"><a href="linear-models.html#CGM"><i class="fa fa-check"></i><b>5.3</b> A versus B: Comparison of groups</a><ul>
<li class="chapter" data-level="5.3.1" data-path="linear-models.html"><a href="linear-models.html#dummy_variables"><i class="fa fa-check"></i><b>5.3.1</b> Not stupid: dummy variables</a></li>
<li class="chapter" data-level="5.3.2" data-path="linear-models.html"><a href="linear-models.html#contrasts"><i class="fa fa-check"></i><b>5.3.2</b> Getting it sharper with contrasts [TBC]</a></li>
<li class="chapter" data-level="5.3.3" data-path="linear-models.html"><a href="linear-models.html#sharper-on-the-fly-derived-quantities-tbd"><i class="fa fa-check"></i><b>5.3.3</b> Sharper on the fly: derived quantities [TBD]</a></li>
<li class="chapter" data-level="5.3.4" data-path="linear-models.html"><a href="linear-models.html#exercises-3"><i class="fa fa-check"></i><b>5.3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="linear-models.html"><a href="linear-models.html#putting-it-all-together-multi-predictor-models"><i class="fa fa-check"></i><b>5.4</b> Putting it all together: multi predictor models</a><ul>
<li class="chapter" data-level="5.4.1" data-path="linear-models.html"><a href="linear-models.html#on-surface-multiple-regression-models"><i class="fa fa-check"></i><b>5.4.1</b> On surface: multiple regression models</a></li>
<li class="chapter" data-level="5.4.2" data-path="linear-models.html"><a href="linear-models.html#crossover-multifactorial-models-tbc"><i class="fa fa-check"></i><b>5.4.2</b> Crossover: multifactorial models [TBC]</a></li>
<li class="chapter" data-level="5.4.3" data-path="linear-models.html"><a href="linear-models.html#line-by-line"><i class="fa fa-check"></i><b>5.4.3</b> Line-by-line: regression in groups [TBC]</a></li>
<li class="chapter" data-level="5.4.4" data-path="linear-models.html"><a href="linear-models.html#residual-analysis"><i class="fa fa-check"></i><b>5.4.4</b> Residual analysis</a></li>
<li class="chapter" data-level="5.4.5" data-path="linear-models.html"><a href="linear-models.html#how-to-plot-mpm-tbc-move-to-interaction-effects"><i class="fa fa-check"></i><b>5.4.5</b> How to plot MPM? [TBC, move to Interaction effects]</a></li>
<li class="chapter" data-level="5.4.6" data-path="linear-models.html"><a href="linear-models.html#empirical-versus-statistical-control"><i class="fa fa-check"></i><b>5.4.6</b> Empirical versus statistical control</a></li>
<li class="chapter" data-level="5.4.7" data-path="linear-models.html"><a href="linear-models.html#exercises-4"><i class="fa fa-check"></i><b>5.4.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="linear-models.html"><a href="linear-models.html#interaction-effects"><i class="fa fa-check"></i><b>5.5</b> Interaction effects</a><ul>
<li class="chapter" data-level="5.5.1" data-path="linear-models.html"><a href="linear-models.html#differential_design_effects"><i class="fa fa-check"></i><b>5.5.1</b> Users differ: differential design effects</a></li>
<li class="chapter" data-level="5.5.2" data-path="linear-models.html"><a href="linear-models.html#hitting-the-boundaries-of-saturation"><i class="fa fa-check"></i><b>5.5.2</b> Hitting the boundaries of saturation</a></li>
<li class="chapter" data-level="5.5.3" data-path="linear-models.html"><a href="linear-models.html#more-than-the-sum-amplification"><i class="fa fa-check"></i><b>5.5.3</b> More than the sum: amplification</a></li>
<li class="chapter" data-level="5.5.4" data-path="linear-models.html"><a href="linear-models.html#theoretically-interesting-interaction-effects-edit"><i class="fa fa-check"></i><b>5.5.4</b> Theoretically interesting interaction effects [EDIT]</a></li>
<li class="chapter" data-level="5.5.5" data-path="linear-models.html"><a href="linear-models.html#exercises-5"><i class="fa fa-check"></i><b>5.5.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="linear-models.html"><a href="linear-models.html#polynomial_regression"><i class="fa fa-check"></i><b>5.6</b> Doing the rollercoaster: polynomial regression</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multilevel-models.html"><a href="multilevel-models.html"><i class="fa fa-check"></i><b>6</b> Multilevel models</a><ul>
<li class="chapter" data-level="6.1" data-path="multilevel-models.html"><a href="multilevel-models.html#average-neverage"><i class="fa fa-check"></i><b>6.1</b> Average? Neverage!</a></li>
<li class="chapter" data-level="6.2" data-path="multilevel-models.html"><a href="multilevel-models.html#the-human-factor-intercept-random-effects"><i class="fa fa-check"></i><b>6.2</b> The Human Factor: Intercept random effects</a></li>
<li class="chapter" data-level="6.3" data-path="multilevel-models.html"><a href="multilevel-models.html#designs-and-other-non-human-populations"><i class="fa fa-check"></i><b>6.3</b> Designs and other non-human populations</a></li>
<li class="chapter" data-level="6.4" data-path="multilevel-models.html"><a href="multilevel-models.html#crossover"><i class="fa fa-check"></i><b>6.4</b> Crossover: Testing Egans assumption</a></li>
<li class="chapter" data-level="6.5" data-path="multilevel-models.html"><a href="multilevel-models.html#measuring-entities-psychometric-applications-tbc"><i class="fa fa-check"></i><b>6.5</b> Measuring entities: psychometric applications [TBC]</a></li>
<li class="chapter" data-level="6.6" data-path="multilevel-models.html"><a href="multilevel-models.html#nested-random-effects"><i class="fa fa-check"></i><b>6.6</b> Nested random effects</a></li>
<li class="chapter" data-level="6.7" data-path="multilevel-models.html"><a href="multilevel-models.html#what-are-random-effects-on-pooling-and-shrinkage"><i class="fa fa-check"></i><b>6.7</b> What are random effects? On pooling and shrinkage</a></li>
<li class="chapter" data-level="6.8" data-path="multilevel-models.html"><a href="multilevel-models.html#slope_RE"><i class="fa fa-check"></i><b>6.8</b> Variance in variation: slope random effects [TBC]</a></li>
<li class="chapter" data-level="6.9" data-path="multilevel-models.html"><a href="multilevel-models.html#re_correlations"><i class="fa fa-check"></i><b>6.9</b> Growing with random effects correlations [TBD]</a></li>
<li class="chapter" data-level="6.10" data-path="multilevel-models.html"><a href="multilevel-models.html#advanced-tricks"><i class="fa fa-check"></i><b>6.10</b> Advanced tricks</a></li>
<li class="chapter" data-level="6.11" data-path="multilevel-models.html"><a href="multilevel-models.html#exercises-7"><i class="fa fa-check"></i><b>6.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="GLM.html"><a href="GLM.html"><i class="fa fa-check"></i><b>7</b> Generalized Linear Models</a><ul>
<li class="chapter" data-level="7.1" data-path="GLM.html"><a href="GLM.html#debunking-the-gaussian-linear-model"><i class="fa fa-check"></i><b>7.1</b> Debunking the Gaussian linear model</a><ul>
<li class="chapter" data-level="7.1.1" data-path="GLM.html"><a href="GLM.html#assuming-linearity"><i class="fa fa-check"></i><b>7.1.1</b> Assuming linearity</a></li>
<li class="chapter" data-level="7.1.2" data-path="GLM.html"><a href="GLM.html#assuming-normal-distribution-of-randomness"><i class="fa fa-check"></i><b>7.1.2</b> Assuming Normal distribution of randomness</a></li>
<li class="chapter" data-level="7.1.3" data-path="GLM.html"><a href="GLM.html#assume-constant-variance"><i class="fa fa-check"></i><b>7.1.3</b> Assuming constant variance of randomness</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="GLM.html"><a href="GLM.html#glm_concepts"><i class="fa fa-check"></i><b>7.2</b> Elements of Generalized Linear Models</a><ul>
<li class="chapter" data-level="7.2.1" data-path="GLM.html"><a href="GLM.html#re-linking-linearity-relinking_linearity-tbc"><i class="fa fa-check"></i><b>7.2.1</b> Re-linking linearity (#relinking_linearity) [TBC]</a></li>
<li class="chapter" data-level="7.2.2" data-path="GLM.html"><a href="GLM.html#choosing-patterns-of-randomness-choosing_randomness"><i class="fa fa-check"></i><b>7.2.2</b> Choosing patterns of randomness (#choosing_randomness)</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="GLM.html"><a href="GLM.html#case-user-testing-infusion-pumps"><i class="fa fa-check"></i><b>7.3</b> Case: user testing infusion pumps</a></li>
<li class="chapter" data-level="7.4" data-path="GLM.html"><a href="GLM.html#count_data"><i class="fa fa-check"></i><b>7.4</b> Count data</a><ul>
<li class="chapter" data-level="7.4.1" data-path="GLM.html"><a href="GLM.html#poisson-regression"><i class="fa fa-check"></i><b>7.4.1</b> Poisson regression</a></li>
<li class="chapter" data-level="7.4.2" data-path="GLM.html"><a href="GLM.html#logistic-aka-binomial-regression-logistic_regression"><i class="fa fa-check"></i><b>7.4.2</b> Logistic (aka Binomial) regression (#logistic_regression)</a></li>
<li class="chapter" data-level="7.4.3" data-path="GLM.html"><a href="GLM.html#modelling-overdispersion"><i class="fa fa-check"></i><b>7.4.3</b> Modelling overdispersion</a></li>
<li class="chapter" data-level="7.4.4" data-path="GLM.html"><a href="GLM.html#exercises-8"><i class="fa fa-check"></i><b>7.4.4</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="GLM.html"><a href="GLM.html#measures_of_time"><i class="fa fa-check"></i><b>7.5</b> Measures of time</a><ul>
<li class="chapter" data-level="7.5.1" data-path="GLM.html"><a href="GLM.html#exponential-regression"><i class="fa fa-check"></i><b>7.5.1</b> Exponential regression</a></li>
<li class="chapter" data-level="7.5.2" data-path="GLM.html"><a href="GLM.html#gamma-regression"><i class="fa fa-check"></i><b>7.5.2</b> Gamma regression</a></li>
<li class="chapter" data-level="7.5.3" data-path="GLM.html"><a href="GLM.html#exgaussian-regression"><i class="fa fa-check"></i><b>7.5.3</b> ExGaussian regression</a></li>
<li class="chapter" data-level="7.5.4" data-path="GLM.html"><a href="GLM.html#literature"><i class="fa fa-check"></i><b>7.5.4</b> Literature</a></li>
<li class="chapter" data-level="7.5.5" data-path="GLM.html"><a href="GLM.html#exercises-9"><i class="fa fa-check"></i><b>7.5.5</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="GLM.html"><a href="GLM.html#rating-scales"><i class="fa fa-check"></i><b>7.6</b> Rating scales</a><ul>
<li class="chapter" data-level="7.6.1" data-path="GLM.html"><a href="GLM.html#ordered-logistic-regression"><i class="fa fa-check"></i><b>7.6.1</b> Ordered logistic regression</a></li>
<li class="chapter" data-level="7.6.2" data-path="GLM.html"><a href="GLM.html#beta-regression"><i class="fa fa-check"></i><b>7.6.2</b> Beta regression</a></li>
<li class="chapter" data-level="7.6.3" data-path="GLM.html"><a href="GLM.html#distributional-models"><i class="fa fa-check"></i><b>7.6.3</b> Distributional models</a></li>
<li class="chapter" data-level="7.6.4" data-path="GLM.html"><a href="GLM.html#exercises-10"><i class="fa fa-check"></i><b>7.6.4</b> Exercises</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">New statistics for the design researcher</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multilevel-models" class="section level1">
<h1><span class="header-section-number">6</span> Multilevel models</h1>
<p>In the previous chapters we have seen several examples of differential design effects: groups of users responding differently to design conditions, such as font size, noise and emerging technology. Dealing with differential design effects seems straight forward: identify the relevant property, record it and add an interaction effect to the model. Identifying the relevant property is, in fact, a catch-22: how would you know what is relevant before you have conducted the research, actually. Researchers routinely record basic demographic properties such as age and gender, but these frequently show little effects, or the effects are obvious, i.e. not interesting. In addition, such predictors are rarely more than approximations of the properties that make the difference, really. Older people have weaker vision <em>by tendency</em>, but the individual differences in any age group are immense. Boys tend to be more technophile, but there exist some real geek girls, too.</p>
<p>Identifying properties that matter upfront requires careful review of past research or deep theorizing, and even then it remains guesswork. Presumably, hundreds of studies attempted to explain differences in usage patterns or performance by all sorts of psychological predictors, with often limited results. That is a big problem in design research, as variation in performance can be huge and good predictors are urgently needed. Identifying the mental origins of being fast versus slow, or motivated versus bored, is extremely useful to improve the design of systems to be more inclusive or engaging.</p>
<p>As we will see in this chapter, individual differences can be accounted for and measured accurately without any theoretically derived predictors. For researchers trained in experimental social sciences it may require a bit of Zen to let go of theory-driven reasoning, as it is always tempting to ask for the <em>why</em>. But in applied evaluation studies, what we often really need to know is by <em>how much</em> users vary. The key to measuring variation in a population is to create models that operate on the level of participants, in addition to the population level, for example</p>
<ul>
<li>on population level, users prefer design B over A on average (<span class="math inline">\(\beta_1 = 20\)</span>)</li>
<li>on the participant-level, participant <span class="math inline">\(i\)</span> preferred B over A (<span class="math inline">\(\beta_{1i} = 20\)</span>), <span class="math inline">\(j\)</span> preferred A over B (<span class="math inline">\(\beta_{1j} = -5\)</span>), …</li>
</ul>
<p>See how on the participant level, everyone gets their own estimate for preference (<span class="math inline">\(\beta_{1\cdot}\)</span>). The key to estimating individual parameters is simply to regard participant (<code>Part</code>) a grouping variable on its own, and introduce it as a factor to the linear model. As we will see, it is <em>almost</em> that easy. The additional idea is that the levels of the factor, hence the individuals, are part of a <em>population</em>. While researchers in fundamental social sciences typically ignore individual variation, there is an independent branch in Psychology called <em>psychometrics</em> that deals with precisely that: constructing tests to measuring the individual. Think of IQ tests, which are constructed to have an average of 100, with 67% humans falling in the range 85 - 115. More extreme values become increasingly infrequent. From this perspective, it becomes clear what a population is: a set of entities that do vary but clump around a typical value. These two simple ideas, participants are factors, too, and are part of a population, form what is commonly called <em>random factors</em>: a factor where levels are drawn from an overarching distribution, usually the Gaussian. This distribution is estimated simultaneously to the individual parameters (<span class="math inline">\(\beta_{1\cdot}\)</span>), which has some interesting consequences, as we will see when discussing shrinkage.</p>
<p>Typically, fixed and random effects appear together in a linear mixed-effects model. As we will see, it depends on the research question whether the researcher capitalizes on the participant-level effects, the average outcome or the variation in the population. As we will also see, the idea of random effects transfers with grace to <em>non-human populations</em>, such as designs or questionnaire items. But, first, let me give you an illustration, why caring for individual differences is not just an added value, that you may take or leave, but a necessary perspective to avoid severely wrong conclusions.</p>
<div id="average-neverage" class="section level2">
<h2><span class="header-section-number">6.1</span> Average? Neverage!</h2>
<p>Many studies in design research pretend that all users are alike. This borrowed from experimental social science research. Seminal studies in cognitive psychology and social psychology claim mental structures or processes that hold for all humans. That is the very paradigm of fundamental psychology and many researchers ground their theorizing and experimentation on it. And indeed, several properties of human information processing have been replicated under such diverse conditions that one can assume that they are general. For example, the Stroop observation has been observed a hundred times in various population subgroups [REF], situations [REF] and variations.</p>
<p>The treatments in such experiments can be simplistic to an extreme. Often, participants are asked to respond to colored geometric shapes that light up on a black background by simple key presses. This is called <em>reductionism</em> and it has lead to at least some insights how the human mind works. As much as design researchers should draw upon psychological theory, as little useful the reductionist paradigm is, as designs must work in real world situations, often in many different ones, and highly controlled lab experiments just bear to little resemblance to the real world. In particular, by no means can we expect all usersalike to one or more designs. Their minds are complex, too, obscure and unpredictable besides.</p>
<blockquote>
<p>Our minds are not run as top - down dictatorships; they are rambunctious parliaments, populated by squabbling factions and caucuses, with much more going on beneath the surface than our conscious awareness ever accesses. (Carroll, Sean. The Big Picture (Kindle Locations 5029-5031). Oneworld Publications. Kindle Edition.)</p>
</blockquote>
<p>Let me get it straight: People differ! If you plan to move from design A to B, or any other design choice, its is a good idea to also regard how much people vary. If your research question refers to any mental process or its change, the only solid way is to observe how one-and-the-same individuals behave on all conditions. That means within-subject designs should be the rule, not the exception. In contrast, doing a between-subject design is a potential mistake and requires good justification. The following case illustrates how terribly things can go wrong, when within-subject processes are examined in a between-subject manner:</p>
<p>Imagine you set out to determine the association between typing speed and errors. It is common sense that quality decreases with speed, so a positive correlation is expected. During the epxeriment, participants get a number of texts to type. With the first trial they are instructed to type at a relaxed speed. With every further trial they were asked to type slightly faster than at the trial before. The expectation is that</p>
<blockquote>
<p>The faster a person types, the more errors occur</p>
</blockquote>
<p>In terms of statistical skills, the researcher is familiar with linear models, and is aware of the fact, that these may not be applied for repeated measures. Therefore our researcher first averages the scores across participants and receives a data set with a neat 30 data points, one per trial. A first exploratory plot reveals a bizarre relation: it seems that the faster participants type, the less error they make. That is completely against expectations, as there almost always is a trade-off between speed and accuracy.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(Typing)

Type_1_avg <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> speed,
             <span class="dt">y =</span> error)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">se =</span> F)</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/Typing_average-1.png" width="672" /></p>
<p>Could it be true that the faster a person types, the less errors happen? Of course not. The problem is how precisely we ask the question. When averaging over persons, we actually answer a different question, which is on a <em>population-level</em>: Do persons who can type faster make fewer errors? This question sees every person as one data point with two performance measures, speed and errors, both representing the ability to type. Now, the above results make more sense: people, who are trained in typing are at the same time fast and more accurate. But, what the experiment was out for is the trade-off between speed and accuracy <em>within a person</em>. The experiment provokes this trade-off by asking the same person to accelerate in typing. And, when we visualize the results on an individual level, the speed-accuracy trade-off becomes immediately visible:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Type_<span class="dv">1</span> <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> speed,
             <span class="dt">y =</span> error,
             <span class="dt">group =</span> Part)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">se =</span> F, <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="kw">aes</span>(<span class="dt">col =</span> <span class="st">&quot;within participant&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">data =</span> Type_1_avg, 
              <span class="kw">aes</span>(<span class="dt">col =</span> <span class="st">&quot;between participant&quot;</span>, <span class="dt">x =</span> speed, <span class="dt">y =</span> error, <span class="dt">group =</span> <span class="ot">NA</span>), 
              <span class="dt">se =</span> F, <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/Typing_individual-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(Typing)</code></pre></div>
<p>The example here is constructed to be extreme: the population-level effect has the opposite direction of individual level effects. However, the situation is fully plausible and points us to an important principle: Whenever a research question capitalizes on a change in mental state or behaviour, the only solid way to research is a within-subject design. Therefore again: treating averaged data as if it represents within-persons changes is a severe mistake. In the A/B case, for example, one must always be clear about the level. Is it true that</p>
<ul>
<li>on average, users prefer B over A?</li>
<li>or all users individually prefer B over A?</li>
</ul>
<p>The bizzare situation with the Typing study will have to wait, because we will need all elements of multilevel modelling to resolve it. However, the figure above features the core elements of mutlilevel models:</p>
<ul>
<li>persons have different levels for errors at relaxed typing (varying intercepts)</li>
<li>persons differ in how much the error frequency goes up with speed (varying slopes)</li>
<li>the better a person performs at relaxed typing, the stronger the number of errors goes up when the person types faster (correlated ramdom effects)</li>
</ul>
</div>
<div id="the-human-factor-intercept-random-effects" class="section level2">
<h2><span class="header-section-number">6.2</span> The Human Factor: Intercept random effects</h2>
<p>Design science fundamentally deals with interaction between systems and humans. Every measure we take in a design study is an encounter of an individual with a system. As people differ in almost every aspect, it is likely that people differ in how they use a system. In the previous chapter we have already dealt with differences between users: in the BrowsingAB case, we compared two designs in how inclusive they are with respect to elderly users. The data set included further variables, education and gender, that may help to predict performance.</p>
<p>Imagine, you had gathered no predictors at all and observed massive amount of variation in performance. It is reasonable to assume that much of this variation stems from individual differences. That, in turn would mean that a fraction of users perform extremely well, whereas many users fail miserably. If that were true, you would give the advice to invest into redesign that is more inclusive, ironing out the differences, would you not? To make your point, you had to prove that individual differences are the main source of variation.</p>
<p>At first, one might think that the grand mean model would do, take <span class="math inline">\(\beta_0\)</span> as the population mean and <span class="math inline">\(\sigma\)</span> as a measure for individual variation. Unfortunately, it is not valid to take the residual variance as variance between individuals, the reason being that random variation captured by <span class="math inline">\(\sigma\)</span> is composed of multiple sources, in particular:</p>
<ul>
<li>inter-individual variation</li>
<li>intra-individual variation, e.g. by different levels of energy over the day</li>
<li>variations in situations, e.g. responsiveness of website</li>
<li>inaccuracy of measures</li>
</ul>
<p>What is needed, is a way to separate the variation of participants from the rest. Reconsider the principles of model formulations: the likelihood captures what is repeatable, what does not repeat goes to the random term. For the problem of identifying individual differences, we simply apply this principle: to pull out a factor from the random term, repetition is needed. For estimating users’ individual performance level, all that is needed is repeated measures.</p>
<p>Imagine, a pre-study to BrowsingAB was done on the existing design A. Data was gathered in live operation of the website. Real users were tracked on eight tasks. While it was possible to identify the task a user was on and identity of users could be tracked, too. However, as a consequence of privacy protection not a single demographic variable could be gathered. With the simulation function of the BrowsingAB case environment we generate a new data set <code>SOV</code> (sources of variance), reduce it to design A and remove all predictors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(BrowsingAB)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n_Part =<span class="st"> </span><span class="dv">25</span>
n_Task =<span class="st"> </span><span class="dv">8</span>
n_Obs =<span class="st"> </span>n_Part <span class="op">*</span><span class="st"> </span>n_Task


SOV &lt;-
<span class="kw">simulate</span>(n_Part, n_Task) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="kw">filter</span>(Design <span class="op">==</span><span class="st"> &quot;A&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="kw">select</span>(Obs, Part, Task, ToT) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">as_tbl_obs</span>()</code></pre></div>
<p>We start with some data exploration. The first question we can ask is:</p>
<blockquote>
<p>What is the average ToT in the population?</p>
</blockquote>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SOV <span class="op">%&gt;%</span><span class="st"> </span>
<span class="kw">summarize</span>(<span class="dt">mean_Pop =</span> <span class="kw">mean</span>(ToT)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">mean_Pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">146</td>
</tr>
</tbody>
</table>
<p>This question is rather global and does not refer to any individuals in the population. The following question does:</p>
<blockquote>
<p>What is the average ToT of individual participants?</p>
</blockquote>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SOV <span class="op">%&gt;%</span><span class="st"> </span>
<span class="kw">group_by</span>(Part) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="kw">summarize</span>(<span class="dt">mean_Part =</span> <span class="kw">mean</span>(ToT)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Part</th>
<th align="right">mean_Part</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">7</td>
<td align="right">145</td>
</tr>
<tr class="even">
<td align="left">14</td>
<td align="right">101</td>
</tr>
<tr class="odd">
<td align="left">6</td>
<td align="right">128</td>
</tr>
<tr class="even">
<td align="left">22</td>
<td align="right">127</td>
</tr>
<tr class="odd">
<td align="left">12</td>
<td align="right">148</td>
</tr>
</tbody>
</table>
<p>This question differs in that it is <em>grouped</em> by participant. Now, that we have the individual means, we can plot the variation in task performance. For comparison, the overall variation is added to the plot. It is apparent that individual differences make only part of the overall variance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">G_sources_variation &lt;-
<span class="st">  </span>SOV <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(Part) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_Part =</span> <span class="kw">mean</span>(ToT)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_Part)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">data =</span> SOV, <span class="kw">aes</span>(<span class="dt">x =</span> ToT, <span class="dt">y=</span>..scaled.., 
                               <span class="dt">fill =</span> <span class="st">&quot;total&quot;</span>),<span class="dt">alpha =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> <span class="st">&quot;user&quot;</span>, <span class="dt">y=</span>..scaled..),<span class="dt">alpha =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">fill =</span> <span class="st">&quot;Variation&quot;</span>)
G_sources_variation</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/re_variation-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(BrowsingAB)</code></pre></div>
<p>Above, we have claimed that our data set is bare of predictors. Is it? The variable <code>Part</code> groups observations by participant identity and therefore is a plain factor. If we can compute user means like above, what keeps us from adding a factor, like:</p>
<p><code>SOV ~ 1 + Part</code></p>
<p>While formally, a participant is just a group of observations, there is one apparent, one practical and one subtle difference compared to factors as we know them so far. The apparent difference is that before we had just very few levels and many observations. With participants we had to estimate dozens or hundreds of coefficients with just very few observations per level. In consequence, the posterior distribution will become spread out like butter on a toast and certainty will be abysmal. The practical difference is that, while we are interested in the overall variation, the ability of individual users is rather uninteresting. We actually have no use for dozens of user ability scores. The subtle difference is that users form a population. That sounds rather obviuous than subtle, but is key for the solution once we understand what being <em>member of a population</em> means, statistically. I will give a brief account here and return to the topic in a later section.</p>
<p>Imagine the following situation: you are seated in a university bistro and you get the task to guess the intelligence quotient of every person entering the bistro. After every trial you are disclosed the real IQ of the person. You know that the average IQ is 100 and you give a bonus of 5 owing to the fact it is at a university. The first five persons have the IQs:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">IQ &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">106</span>, <span class="dv">108</span>, <span class="dv">103</span>, <span class="dv">115</span>, <span class="dv">110</span>)</code></pre></div>
<p>It seems the bonus of five is an understatement and the average is closer to 110. You adjust your best guess accordingly. That sounds trivial, but for the specification of a regression model it is not. The crucial point is that any guess <span class="math inline">\(k\)</span> depends on the information you received on trials <span class="math inline">\(1...(k-1)\)</span>. Review the model formulation for comparison of means models. There is nothing in the linear term that transfers information between levels of factors. The group means are estimated in complete independence.</p>
<p>The key is is that participants are <em>members of a population</em>. In a reasonably large population, extremes such as an IQ of 160 will eventually happen, but they are very unlikely. by far most people, roughly two thirds, are clumped together in the range 85 to 115. Imagine you are travelling to an African country you have never heard of before. Africa has the richest gene pool of all and ethnicies differ a lot in tallness and skin tone. Once you have left the plane and saw a few people, you get an impression of how tall and dark people are in this place. The same principle holds for human attributes or capabilities in design research. Having seen a bunch of participants completing a task between two and five minutes gives a best guess for the next particiant. It is not excluded that this person will need 25 minutes or 20 seconds for the task, but it is less likely.</p>
<p>Factors where the individual levels vary, but are more or less clumped around a population mean are best modelled as <em>random factors</em> and the individual levels are called <em>random effects</em>. Random effects enter the likelihood of the linear model specification in a similar additive way as fixed effects. The difference is that the levels are assumed to stem from a normal distribution, which represents the clumping. The mean of this distribution is zero, similar to the distribution of residuals, but the standard deviation of this distribution, representing the amount of variation in the population, is <em>estimated alongside</em> the individual levels.</p>
<p>For the pre-study we have simulated above we can formulate a GM model with participant-level random effect <span class="math inline">\(\beta_{p0}\)</span> as follows:</p>
<p><span class="math display">\[
\mu_i = \beta_0 + x_p\beta_{p0}\\
\beta_{p0} \sim N(0, \sigma_{p0})\\
y_i \sim N(\mu_i, \sigma_\epsilon)
\]</span></p>
<p>There will be as many parameters <span class="math inline">\(\beta_{p0}\)</span>, as there were users in the sample, and they have all become part of the likelihood. The second term describes the distribution of the levels. And finally, there is the usual random term. Before we examine further features of the model, let’s run it. In the package <code>rstanarm</code>, the command <code>stan_glmer()</code> is dedicated to estimate mixed-effects models with the extended formula syntax.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(BrowsingAB)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_1_SOV &lt;-<span class="st"> </span><span class="kw">stan_glmer</span>(ToT <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Part), <span class="dt">data =</span> SOV)
P_1_SOV &lt;-<span class="st"> </span><span class="kw">posterior</span>(M_1_SOV)</code></pre></div>
<p>The posterior of the mixed-effects model contains four types of variables:</p>
<ol style="list-style-type: decimal">
<li>the <em>fixed effect</em> captures the population average (Intercept)</li>
<li><em>random effects</em> capture how individual participants deviate from the population mean</li>
<li><em>random factor variation</em> (or group effects) captures the overall variation in the population.</li>
<li>the residual standard deviation captures the amount of noise</li>
</ol>
<p>With the <code>bayr</code> package these parameters can be extracted using the respective commands:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fixef</span>(P_1_SOV)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="left">type</th>
<th align="left">fixef</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">M_1_SOV</td>
<td align="left">fixef</td>
<td align="left">Intercept</td>
<td align="right">146</td>
<td align="right">133</td>
<td align="right">159</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># ranef(P_1_SOV) # a long list</span>
<span class="kw">grpef</span>(P_1_SOV)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="left">type</th>
<th align="left">fixef</th>
<th align="left">re_factor</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">M_1_SOV</td>
<td align="left">grpef</td>
<td align="left">Intercept</td>
<td align="left">Part</td>
<td align="right">26.1</td>
<td align="right">15.5</td>
<td align="right">40.4</td>
</tr>
</tbody>
</table>
<p>Random effects are factors and enter the model formula just as linear terms. What sets them apart, is that they are estimated together with the overarching Gaussian distribution. To indicate that to the regression engine, a dedicated syntax is used in the model formula (recall that <code>1</code> represents the intercept parameter):</p>
<p><code>(1|Part)</code></p>
<p>In probability theory expressions, such as famous Bayes theorem, the <code>|</code> symbol means that something to the left is conditional on something to the right. Random effects can easily be conceived as such conditional effects. Left of the <code>|</code> is the fixed effects that is conditional on (i.e. varies by) the factor to the right. In the simplest form the varying effect is the intercept and in the case here could be spoken of as:</p>
<blockquote>
<p>ToT depends on the participant you are looking at</p>
</blockquote>
<p>Speaking of factors: so far, we have used <em>treatment contrasts</em> most of the time, which represent the difference towards a reference level. Analogue to a factor model, we could estimate the first participants performance level and make it the reference group, intercept <span class="math inline">\(\beta_0\)</span>. All other average scores, we would express as differences to the reference participant. This seems odd and, indeed, has two disadvantages: first, whom are we to select as the reference participant? The choice would be arbitrary, unless we wanted to compare brain sizes against the gray matter of Albert Einstein, perhaps. Second, most of the time the researcher is after the factor variation rather than differences between any two individuals, which is inconvenient to compute from treatment contrasts.</p>
<p>The solution is to use a different contrast coding for random factors: <em>deviation contrasts</em> represent the individual effects as <em>difference (<span class="math inline">\(\delta\)</span>) towards the population mean</em>. As the population mean is represented by the respective fixed effect, we can compute the absolute individual predictions by adding the fixef effect to the random effect:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data_frame</span>(<span class="dt">mu_i =</span> <span class="kw">ranef</span>(P_1_SOV)<span class="op">$</span>center <span class="op">+</span><span class="st"> </span>
<span class="st">             </span><span class="kw">fixef</span>(P_1_SOV)<span class="op">$</span>center) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mu_i)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>()</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Finally, we can assess the initial question: is individual differences a significant component of all variation in the experiment? Assessing the impact of variation is not as straight-forward as with fixed effects. One heuristic is to compare it against the residual variance, which is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">T_sov_vc &lt;-<span class="st"> </span><span class="kw">coef</span>(P_1_SOV, <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;grpef&quot;</span>, <span class="st">&quot;disp&quot;</span>))
T_sov_vc</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">parameter</th>
<th align="left">type</th>
<th align="left">fixef</th>
<th align="left">re_factor</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sigma_resid</td>
<td align="left">disp</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="right">54.5</td>
<td align="right">49.3</td>
<td align="right">60.9</td>
</tr>
<tr class="even">
<td align="left">Sigma[Part:Intercept,(Intercept)]</td>
<td align="left">grpef</td>
<td align="left">Intercept</td>
<td align="left">Part</td>
<td align="right">26.1</td>
<td align="right">15.5</td>
<td align="right">40.4</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(BrowsingAB)</code></pre></div>
<p>The variation due to individual differences is half of the noise, which is considerable. It seems in order to further investigate of why and how users vary in performance, as this is the key to improving the design for all users.</p>
<p><strong>Exercises</strong>:</p>
</div>
<div id="designs-and-other-non-human-populations" class="section level2">
<h2><span class="header-section-number">6.3</span> Designs and other non-human populations</h2>
<p>With the introduction of random effects design researchers can make more precise statements about how a design affects the population of users. The population-level average effect gets amended by a measure of variation. Only when this variation is small can one conclude that the effect is homogenous for the whole population. In the BrowsingAB case, this gives valuable information on how well this particular design serves the population of users and whether one should be satisfied with it or not. This is a typical research question in applied design research where one seeks to choose one from a small set of designs. Generally, A/B studies seek to answer the question: <em>is one design better for the user population?</em>. This question has two entities: the user and the design. However, it is not symmetric, as users are provided as a sample from which one wishes to generalize, whereas the two designs are exhaustive. There is the choice between the two and they are both present.</p>
<p>But, that is not all there is in design research. Many studies in, what one could call <em>fundamental design research</em> seek to uncover general laws of design that may guide future system development. Fundamental design research is not concerned with choosing between individual designs, whether they are good enough or not, but with seperating the population of possible designs into good ones and the bad. A/B studies, as we know them, are not adequate to answer such questions, simply because there is no reasonable way to generalize from a sample of two to all possible designs. This would only be possible under one strict constraint: the design property in question, let’s say font size, must be the only property where A and B differ. Under this constraint, the population of designs is exactly all designs that are constant except for font size. It is left to the reader to contemplate why that is of little value.</p>
<p>If the research question is fundamental, aiming at general conclusions on design, it is almost inevitable to test it on a larger sample of designs. Once we start speaking about samples of designs, there must be a <em>population of designs</em>, too. The term population suggests a larger set of entities, and in fact many application domains have an abundance of existing designs and a universe of possible designs. Just to name a few: there exist dozens of note taking apps for mobile devices and hundreds of […]. Several classes of websites count thousands of members, such as webshops and municipal websites.</p>
<p>Even in highly standardized domains such as automotive cockpits the differences between generations, manufacturers and models are noticable to be called individuals from a population. That is precisely the idea of a random effect: entities vary around a clump of commonalities. In consequence, when testing a fundamental design rule, like <em>large fonts are better to read</em>, the proposed research strategy is to sample from the population of websites, classify sample members by font size, and test every design with a sample of users. Given our definition of random effects it is easy to see that the regression model will contain two random effects (at least), one across users, the other across websites. More on that later.</p>
<p>It does not stop here. While design research is clearly about the user-design encounter, other research entities exist that we could call a population. The most routinely used <em>non-human populations</em> in design research, besides <em>designs</em>, are <em>tasks</em>, <em>situations</em> and <em>questionnaire items</em>. We briefly characterize the latter three and proceed to a case study that employs three population at once.</p>
<p><em>Tasks:</em> Modern informational websites contain thousands of information pieces and finding every one of those can be considered a task. At the same time, it is impossible to cover them all in one study, such that sampling a few is inevitable. We will never be able to tell the performance of every task, but using random effects, it is possible to estimate the variance of tasks. Is that valuable information? Probably it is in many cases, as we would not easily accept a design that prioritizes on a few items at the expense of many others, which are extremely hard to find.</p>
<p><em>Situations:</em> With the emerge of the web, practically everyone started using computers to find any information. With the more recent break through in mobile computing, everyone is doing everything using a computer in almost every situation. People chat, listen to music and play games during meals, classes and while watching television. They let themselves being lulled into sleep, which is tracked and interrupted by smart alarms. Smartphones are being used on trains, while driving cars and bikes, however dangerous that might be, and not even the most private situations are spared. Does the usability of messaging, navigation and e-commerce apps generalize across situations? Again, a study to examine performance across situations would best sample from a population of situations.</p>
<p><em>Questionnaire items:</em> Most design researchers cannot refrain from using questionnaires to evaluate certain aspects of their designs. I do not refrain from being very critical about that, however: a well constructed scale (which unfortunately is rather rule than exception in design research) consists of a set of items that trigger similar responses. At the same time, it is desireable that items are unsimilar to a degree, as that establishes good discrimination across a wide range. In ability tests, for example to assess people’s intelligence or math skills, test items are constructed to vary in difficulty. The more ability a person has, the more likely will a very difficult item be solved correctly. In design research, rating scales cover concepts such as perceived mental workload, perceived usability, beauty or trustworthiness. Items of such scales differ in how extreme the proposition is, like the following three items that could belong to a scale for aesthetic perception:</p>
<ol style="list-style-type: decimal">
<li>The design is not particularly ugly.</li>
<li>The design is pretty.</li>
<li>The design is a piece of art.</li>
</ol>
<p>For any design it is rather difficult to get a positive response on item 3, whereas item 1 is little of a hurdle. So, if one thinks of all possible propositions about beauty, any scale is composed of a sample from the population of beauty propositions.</p>
<p>If we look beyond design research, an abundance of non-human populations can be found in other research disciplines, such as:</p>
<ul>
<li>phonemes in psycholinguistics</li>
<li>test items in a psychometrics</li>
<li>pictures of faces in face recognition research</li>
<li>products in consumer research</li>
<li>patches of land in agricultural studies</li>
<li>flowers in biology</li>
</ul>
<p>However, most of the time these one or two of these populations are involved at once, whereas in design research the encounter of three is rather typical, and not even the limit, as we will see in the following case study</p>
</div>
<div id="crossover" class="section level2">
<h2><span class="header-section-number">6.4</span> Crossover: Testing Egans assumption</h2>
<p>In design research, the encounter of users and designs is almost inevitable. All sampling schemes with an encounter of otherwise independent populations produce so called <em>cross-classified random effects</em> (CRE). Random effects, that is the individual entities in the sample, are usually of lesser interest, but the group-level variation is a natural measure of diversity in the sample. When performance is diverse, we gain little faith that the situation serves all users well.</p>
<p>But, is variance in performance due to diversity of users, necessarily? At least this is what Dennis Egan claimed almost three decades ago:</p>
<blockquote>
<p>‘differences among people usually account for much more variability in performance than differences in system designs’ <a href="#fn2" class="footnoteRef" id="fnref2"><sup>2</sup></a></p>
</blockquote>
<p>This claim has been cited in many papers that regarded individual differences. We were wondering how it would turn out in the third millenium, with the probably most abundant of all application domains: informational websites. For the convenience, we chose the very accessible user population of student users. The design population consisted of ten unversity websites, and ten representative tasks on those were selected. During the experiment, every one of 41 participants completed 10 information search items, being of the folling form:</p>
<blockquote>
<p>On website [utwente.nl] find the program schedule [Biology].</p>
</blockquote>
<p>As this is a real study, there is some inconvenience ahead. Most synthetic case studies so far have outcome measures that are too good to be true. Recall that the distribution of residuals is assumed to be Gaussian in linear regression models. Unfortunately, that is not how the noise of time-on-task measures and other “temporal” variables is shaped, frequently. The cheap trick of <em>log transformation</em> often serves the purpose when not much is at stake. A more disciplined approach to work with time variables is given in [GLM - Time variables].</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(Egan)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">D_egan &lt;-<span class="st"> </span>D_egan <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">logToT =</span> <span class="kw">log</span>(ToT))
D_egan <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as_tbl_obs</span>()</code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="3%" />
<col width="3%" />
<col width="5%" />
<col width="3%" />
<col width="4%" />
<col width="13%" />
<col width="21%" />
<col width="6%" />
<col width="3%" />
<col width="5%" />
<col width="7%" />
<col width="9%" />
<col width="6%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Obs</th>
<th align="right">Part</th>
<th align="left">Gender</th>
<th align="right">age</th>
<th align="right">trial</th>
<th align="left">Design</th>
<th align="left">Task</th>
<th align="left">success</th>
<th align="right">ToT</th>
<th align="right">clicks</th>
<th align="right">returns_hp</th>
<th align="right">return_links</th>
<th align="right">workload</th>
<th align="right">logToT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">391</td>
<td align="right">6</td>
<td align="left">woman</td>
<td align="right">23</td>
<td align="right">5</td>
<td align="left">Erasmus University</td>
<td align="left">student psychologist</td>
<td align="left">TRUE</td>
<td align="right">61</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">3.50</td>
<td align="right">4.11</td>
</tr>
<tr class="even">
<td align="right">82</td>
<td align="right">8</td>
<td align="left">man</td>
<td align="right">22</td>
<td align="right">6</td>
<td align="left">VU Brussel</td>
<td align="left">schedules</td>
<td align="left">TRUE</td>
<td align="right">89</td>
<td align="right">7</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">3.00</td>
<td align="right">4.49</td>
</tr>
<tr class="odd">
<td align="right">392</td>
<td align="right">12</td>
<td align="left">man</td>
<td align="right">24</td>
<td align="right">4</td>
<td align="left">Erasmus University</td>
<td align="left">student psychologist</td>
<td align="left">TRUE</td>
<td align="right">74</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">3.50</td>
<td align="right">4.30</td>
</tr>
<tr class="even">
<td align="right">11</td>
<td align="right">17</td>
<td align="left">woman</td>
<td align="right">21</td>
<td align="right">10</td>
<td align="left">UGent</td>
<td align="left">number of libraries</td>
<td align="left">TRUE</td>
<td align="right">16</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.50</td>
<td align="right">2.77</td>
</tr>
<tr class="odd">
<td align="right">266</td>
<td align="right">28</td>
<td align="left">woman</td>
<td align="right">20</td>
<td align="right">4</td>
<td align="left">UHasselt</td>
<td align="left">ombudsperson or complaints desk</td>
<td align="left">FALSE</td>
<td align="right">70</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.50</td>
<td align="right">4.25</td>
</tr>
<tr class="even">
<td align="right">64</td>
<td align="right">30</td>
<td align="left">man</td>
<td align="right">22</td>
<td align="right">6</td>
<td align="left">Erasmus University</td>
<td align="left">number of faculties</td>
<td align="left">TRUE</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">3.25</td>
<td align="right">1.79</td>
</tr>
<tr class="odd">
<td align="right">172</td>
<td align="right">32</td>
<td align="left">man</td>
<td align="right">23</td>
<td align="right">10</td>
<td align="left">KU Leuven</td>
<td align="left">opening hours library</td>
<td align="left">TRUE</td>
<td align="right">61</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">4.00</td>
<td align="right">4.11</td>
</tr>
<tr class="even">
<td align="right">250</td>
<td align="right">39</td>
<td align="left">woman</td>
<td align="right">21</td>
<td align="right">4</td>
<td align="left">VU Brussel</td>
<td align="left">ombudsperson or complaints desk</td>
<td align="left">TRUE</td>
<td align="right">99</td>
<td align="right">6</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">3.25</td>
<td align="right">4.59</td>
</tr>
</tbody>
</table>
<p>The study originally gathered demographic data and even design features, but for the question of which population varies the most, they are of no further interest. The basic factors in the study were exclusively from human and non-human populations. The latter consisted of designs and tasks in the first place. However, a fourth non-human population has been added: after all, participants get items, which are pairs of tasks and websites. Only seemingly redundant, items will enter the model as a separate random effect. Similar to interaction effects, it may not hold that a task has the same difficulty on every website, and a particular website may present one task in an accessible way, but hide another. The following grid of histogram shows a graphical approximation of the distribution of human and non-human populations. The individual plots were created using the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">  D_egan <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">group_by</span>(Part) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">summarize</span>(<span class="dt">avg_logToT =</span> <span class="kw">mean</span>(logToT)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> avg_logToT)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_histogram</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;distribution of participant average log-times&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">xlim</span>(<span class="fl">1.5</span>,<span class="fl">6.5</span>)</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>There seems to be substantial variation between participants, tasks and items, but very little variation in designs. We build a GMM for the encounter of the four populations.</p>
<p><span class="math display">\[
\mu_i = \beta_0 + x_{Pi}\beta_{P} + x_{Di}\beta_{D} + x_{Ti}\beta_{T} + x_{D:Ti}\beta_{D:T}\\
\beta_{P} \sim N(0, \sigma_{P}) \\
\beta_{D} \sim N(0, \sigma_{D}) \\
\beta_{T} \sim N(0, \sigma_{T}) \\
\beta_{DxT} \sim N(0, \sigma_{DxT})\\
y_i \sim N(\mu, \sigma_\epsilon)\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_<span class="dv">1</span> &lt;-<span class="st"> </span>D_egan <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stan_glmer</span>(logToT <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Part) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Design) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Task) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Design<span class="op">:</span>Task),<span class="dt">data =</span> .)

P_<span class="dv">1</span> &lt;-<span class="st">  </span><span class="kw">posterior</span>(M_<span class="dv">1</span>)</code></pre></div>
<p>The group-level variations are recorded as standard deviations and in Bayesian estimation framework, such variance parameters have their posterior distributions like any other. While the <code>grpef</code> command would conveniently extract a summary of the posteriors, here we choose to get in full contact with the posteriors. In contrast to the linear coefficients, variance parameters are bounded at zero. For this reason, it usually makes little sense to ask whether there is possibly zero variance in a random effect. But, to answer our question, we should rather compare the posterior distributions of all <span class="math inline">\(\sigma_.\)</span>, including the error term (Obs).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">P_<span class="dv">1</span> <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(type <span class="op">==</span><span class="st"> &quot;grpef&quot;</span>  <span class="op">|</span><span class="st"> </span>type <span class="op">==</span><span class="st"> &quot;disp&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">re_factor =</span> <span class="kw">if_else</span>(type <span class="op">==</span><span class="st"> &quot;disp&quot;</span>, <span class="st">&quot;Obs&quot;</span>, re_factor)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(order) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">re_factor =</span> forcats<span class="op">::</span><span class="kw">fct_inorder</span>(re_factor)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> value)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;group-level standard deviation&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_grid</span>(re_factor<span class="op">~</span>.)</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Before we formally evaluate Egan’s claim, there are a few noteworthy remarks on how to read the posteriors, when the parameter is a group-level standard deviation. First, standard deviation is on the same scale as the measured variable. Usually, this makes standard deviations rather intuitive to interpret. This is, <em>unless</em> you have obscured your variable by log transformation, which is the major disadvantage of this procedure. Second, the posterior graph is too easily misinterpreted by confusing the posterior distribution for the group-level distribution. Instead, the amount of variation in a random factor is reflected by the location on the x-axis, while the spread is uncertainty. The population of designs seems to have the lowest variation of all, with users being close second. The observation-level variation (Obs) is nothing but the standard error, <span class="math inline">\(\sigma_\epsilon\)</span>. The observation-level variation sometimes serves well as a reference point to make quantitative statements on variation. For example, there is little confirmation for an overwhelming “users differ!” in this particular study, as there is much more variation from one situation to the other than between participants. A third observation on the posterior plot is that some posteriors are rather certain, e.g. Obs, whereas others are extremely uncertain, especially task-level variation. There is a pattern to explain this: uncertainty of group-level variation estimates heavily depends on sample size from the respective population. Design and Task have a meager <span class="math inline">\(N = 10\)</span>, which is why there is so much uncertainty. At the other extreme, every single one of the 410 observations contributes to estimation of <span class="math inline">\(\sigma_\textrm{Obs}\)</span>, resulting in a rather certain estimate.</p>
<p>All interaction effects are potential assaults on generalizability and so are items (<code>Design:Task</code>). Without this interaction effect, the model would assume that all ten tasks had the same relative difficulty regardless of the website. And the same goes for website. Given the countless possibilities to structure information on a website, this is a bold assumption. It were as if all ten information architects had previously agreed on how well to support any of the tasks. And, as the results show, there is substantial conditional variation, information architects do not fully agree. Regarding the interpretation, the question is: are we willing to add the <em>conditional</em> design effects under what Egan called “designs”, or can only complete websites be called designs, with everything underneath being singular forces that amplify of erase each other? This depends on whether you are an optimist or realist designer. The realist thinks that design is a wicked problem science, where a good design a bunch of reasonable compromises, but is never maximum. You may use large fonts to improve reading speed, but that comes at more scrolling time. You may choose to place an awesome video presentation of your university on its homepage, but you are using costly real estate you could use for other frequently used information. In such a view, a design is a set of carefully calibrated trade-offs and must therefore be taken as a whole.</p>
<p>We proceed with a formal check of Egans claim. It can be stated as: is the random effect variation of users larger than variation of designs, <span class="math inline">\(\sigma_ \textrm{Part} &gt; \sigma_ \textrm{Design}\)</span>. One might be tempted to somehow refer to the figure above and evaluate how much the two posterior distributions overlap. It is much easier than that. Recall, that the joint posterior distribution covers all parameters simultaneously at every MCMC draw. Usually, we evaluate the marginal posterior of one parameter at a time for inference. But, it is equally valid to derive further quantities at every MCMC draw and make inference. In the present case, this quantity is a variable with two states: either Egan’s claim holds, or it does not. The marginal posterior of such a logical variable is of type Bernoulli, capturing the proportion of MCMC draws, where <span class="math inline">\(\sigma_ \textrm{Part} &gt; \sigma_ \textrm{Design}\)</span> holds.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">C_Egan_is_right &lt;-
<span class="st">  </span>P_<span class="dv">1</span> <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(type <span class="op">==</span><span class="st"> &quot;grpef&quot;</span>, re_factor <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Part&quot;</span>, <span class="st">&quot;Design&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(chain, iter, re_factor, value) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">spread</span>(re_factor, value) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">Prop_Egan_is_right =</span> <span class="kw">mean</span>(Part <span class="op">&gt;</span><span class="st"> </span>Design)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">c</span>()

C_Egan_is_right</code></pre></div>
<pre><code>## $Prop_Egan_is_right
## [1] 0.944</code></pre>
<p>A chance of <span class="math inline">\(0.944\)</span> can count as good evidence in favor of Egan’s claim, although it is outshined by other factors, as we have discussed above.</p>
<p>In this case study we have illustrated a number of useful concepts in design research:</p>
<ol style="list-style-type: decimal">
<li>Design research deals with samples of several human and non-human populations at once. Cross-classified random effects models capture these structures.</li>
<li>Group-level standard deviations are captured by the posterior in much the same manner as linear coefficients. The only difference being that they are bounded to zero, which makes null hypothesis useless and can lead to strongly skewed marginal posteriors.</li>
<li>When testing Egan’s claim, we saw how an exotic hypothesis can easily be answered through deriving further quantities from the joint posterior. The same technique we have previously employed to find the troughs in te uncanny valley polynomials.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(Egan)</code></pre></div>
</div>
<div id="measuring-entities-psychometric-applications-tbc" class="section level2">
<h2><span class="header-section-number">6.5</span> Measuring entities: psychometric applications [TBC]</h2>
<p>Traditionally, psychometrics deals with the valid and reliable measurement of person characteristics, such as individual levels of performance, motivation, socio-cognitive attitude and the like. Advanced statistical models have been devised, such as confirmatory factor analysis or item response models. Formally, these applications establish an order among population entities, from low to high. The least one is aiming for is that for any pair of entities <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, we can tell which entity has the more pronounced property. This is called an <em>ordering structure</em>. Few applications even go beyond mere ranking and establish metric interpretations. For example, in an <em>interval-scaled</em> test, the researcher may compare differences between participants.</p>
<p>A psychometric test usually contains several items. For example, a test to measure a child’s arithmetic skills would contain a set of arithmetic problems and a simple test score would be the number of correctly answered items. In design research, self-report questionnaires are routinely used for one of two purposes: first, research questions sometimes involve traits or abilities of users. For example, one could ask how a persons visual-spatial abilities are related to navigation performance, be it in a complex hypertext environment, body cavities during surgical procedures or the scattered displays in air traffic control centers. The researcher would then administer two tests: an innate ability test, such as a mental rotation task and a performance test on, let’s say, the surgical procedure. This is just twice the standard psychometric procedure. Second, in design research one frequently assesses properties of a design by using standardized questionnaires. One example would be the comparison of user experience among a set of e-commerce homepages using scales such as the AttrakDiff (the hedonic dimension). Another example would be to map the uncanny valley effect by letting participants judge a set of artificial faces with a scale to measure eeriness.</p>
<p>We begin with the first case, standard psychometrics to assess user characteristics. A well designed test always employs a set of items. The primary reason for multiple items is a familiar one. In classical test theory, the observed test score <span class="math inline">\(y_i\)</span> for participant <span class="math inline">\(i\)</span> is assumed to be composed of the the true score <span class="math inline">\(\mu_i\)</span> and the measurment error <span class="math inline">\(\epsilon_i\)</span> as:</p>
<p><span class="math display">\[y_i = \mu_i + \epsilon_i\]</span> The same principle holds as for linear models: the researchers aim is to separate <span class="math inline">\(\mu_i\)</span> from <span class="math inline">\(\epsilon_i\)</span> and that is only possible if there is repeated measures.</p>
<p>In our terminology, psychometric models are the encounter of persons and test items. With only two populations involved, the standard psychometric model is a crossover of person and item random affects, a simplification of the quadrupel crossover encountered in the Egan study. What sets psychometric models apart is how random effects are being used. While in the Egan study inference was based on the population-level distribution, i.e. <span class="math inline">\(\sigma_\cdot\)</span>, in psychometrics applications one is interested in the individual scores. If we wanted to compare two individuals, e.g. which of the two is more likely to become the better surgeon based on some ability test, we need individual scores and that is precisely what random effects are on their lowest level.</p>
<p>[semantic Stroop]</p>
<p>Measuring participant performance is a useful application in some design research fields, such as human performance in critical systems, e.g. identify persons with the best talent for being an airspace controller. However, in design research, it is frequently designs that are to be compared. For example, in the Egan case, one might be interested to select the best of the ten website designs, in order to use it as a blueprint. Such a research question is no longer psychometric, literally, but formally the only difference is that participants can be considered test items, rather than test objects. At least, when using ramdom effects for psychometric purposes, there is nothing special about the participant random effects compared to design random effects. Let’s pretend we had conducted the stufy in order to identify a good template for university websites. The following code extracts design random effects posteriors, summarizes them in the usual way and plots.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(Egan)

<span class="kw">ranef</span>(P_<span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(re_factor <span class="op">==</span><span class="st"> &quot;Design&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">Design =</span> re_entity) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Design, <span class="dt">y =</span> center, <span class="dt">ymax =</span> upper, <span class="dt">ymin =</span> lower)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_crossbar</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;log ToT&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>))</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>The most simple form is the Rasch model in IRT, where participants respond to a set of items and the response is either correct or wrong. The outcome variable response is usually coded as 0 = wrong and 1 = correct. Apparently, such a variable does nowhere near satisfy the assumption of linear models. It turns out that the Rasch model can be interpreted as a cross-classified random effects in a <em>logistic regression</em> @ref(logistic_regression). Logistic regression is a member of the General<em>ized</em> Linear family of models, which will be introduced in the next chapter.</p>
<p>As innocent as the Egan study seems, there is some psychometrics involved. First, cognitive workload was measured using the NASA TLX questionnaire which has four items. With four items, we would hardly want to speak of a population. The trick is to view the four items as instantiations from all a virtual set of possible questions (on that matter). A typical question in psychometric research is that of <em>item consistency</em>, which for a small set of items can be measured by the correlation between items. Inter-item correlations indicate that a scale is reliable, which basically means it predicts well. Item correlations are mainly used during scale development, as a criterion to sort out renegade items, those that do not move in accordance with the others.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(Egan)</code></pre></div>
</div>
<div id="nested-random-effects" class="section level2">
<h2><span class="header-section-number">6.6</span> Nested random effects</h2>
<p><em>Nested random effects</em> (NRE) represent nested sampling schemes. A classic example from school research is: a sample of schools is drawn and inside every school a sample of students is selected. Like cross-classified models, nested models consist of multiple levels. The difference is that if one knows the lowest (or: a lower) level of an observation, the next higher level is unambiguous, like:</p>
<ul>
<li>every student is in exactly one class</li>
<li>every participant is from exactly one professional group</li>
</ul>
<p>As we have seen above, cross-classified models play a primary role in design research, due to the user/task/design encounter. NRE are more common in research disciplines where organisation structures or geography plays a role, such as education science (think of the international school comparison studies PISA and TIMMS), organisational psychology or political science.</p>
<p>One case of a nested sampling structures are some of the Comparative Usability Evaluation (CUE) studies, pioneered by Rolf Molich [CUE8]. Different to what the name might suggest, not designs are under investigation in CUE, but usability professionals. The over-arching question in the CUE series is the performance and reliability of usability professionals. Earlier studies sometimes came to devastating results regarding consistency across professional groups when it comes to identifying and reporting usability problems. We always knew, qualitative analysis is much harder to do in an objective way, didn’t we? The CUE8 study lowered the bar, by asking whether several professional groups are able to arrive at consistent measures for time-on-task.</p>
<p>The CUE8 study measured time-on-task in usability tests, which had been conducted by 14 different teams. The original research question was: how reliable are time-on-task measures across teams? All teams were responsible for recruiting their own sample of participants. The nested sampling scheme is therefore: every participant is assigned to exactly one team. The original analysis [CUE8] focussed on the consistency across teams. Using hierarchical random effects, we can extend the analysis. Conjsider the research question: strong systematic variation between teams is considered a sign of low reliability in the field. But, how strong is strong? It is difficult to come up with an absolute standard for inter-team reliability. Again, we can resort to a relative standard: how does the variation between teams compare to variation between individual participants?</p>
<p>Under this perspective, we examine the data. This time, we have real time-on-task data and as so often, it is highly skewed. Again, we use a cheap trick of logarithmic transformation to obtain more symmetric distribution of residuals. The downside is that the outcome variable may not be zero. For time-on-task data this is not an issue. In fact, the original CUE8 data set contains several observations with unrealistically low times. Before proceeding to the model, exploring the original variable <code>ToT</code> on the two levels is in order. The mean ToT is computed for the two random effect levels, participants and teams and plotted in that order.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(CUE8)

D_cue8</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Obs</th>
<th align="left">Team</th>
<th align="left">Part</th>
<th align="left">Condition</th>
<th align="right">SUS</th>
<th align="left">Task</th>
<th align="right">ToT</th>
<th align="right">logToT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">140</td>
<td align="left">B3</td>
<td align="left">28</td>
<td align="left">moderated</td>
<td align="right">87.5</td>
<td align="left">5</td>
<td align="right">120</td>
<td align="right">4.79</td>
</tr>
<tr class="even">
<td align="right">303</td>
<td align="left">D3</td>
<td align="left">61</td>
<td align="left">remote</td>
<td align="right">NA</td>
<td align="left">3</td>
<td align="right">80</td>
<td align="right">4.38</td>
</tr>
<tr class="odd">
<td align="right">377</td>
<td align="left">E3</td>
<td align="left">76</td>
<td align="left">moderated</td>
<td align="right">NA</td>
<td align="left">2</td>
<td align="right">91</td>
<td align="right">4.51</td>
</tr>
<tr class="even">
<td align="right">440</td>
<td align="left">F3</td>
<td align="left">88</td>
<td align="left">remote</td>
<td align="right">NA</td>
<td align="left">5</td>
<td align="right">280</td>
<td align="right">5.63</td>
</tr>
<tr class="odd">
<td align="right">956</td>
<td align="left">K3</td>
<td align="left">192</td>
<td align="left">moderated</td>
<td align="right">97.5</td>
<td align="left">1</td>
<td align="right">611</td>
<td align="right">6.42</td>
</tr>
<tr class="even">
<td align="right">1511</td>
<td align="left">L3</td>
<td align="left">303</td>
<td align="left">remote</td>
<td align="right">80.0</td>
<td align="left">1</td>
<td align="right">111</td>
<td align="right">4.71</td>
</tr>
<tr class="odd">
<td align="right">1897</td>
<td align="left">L3</td>
<td align="left">380</td>
<td align="left">remote</td>
<td align="right">100.0</td>
<td align="left">2</td>
<td align="right">79</td>
<td align="right">4.37</td>
</tr>
<tr class="even">
<td align="right">2416</td>
<td align="left">M3</td>
<td align="left">484</td>
<td align="left">remote</td>
<td align="right">55.0</td>
<td align="left">1</td>
<td align="right">289</td>
<td align="right">5.67</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">D_part_mean &lt;-
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(Part, Condition) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_ToT =</span> <span class="kw">mean</span>(ToT), <span class="dt">na.rm =</span> T,
            <span class="dt">n_Obs =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st">   </span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">Unit =</span> Part) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">percentile =</span> <span class="kw">percent_rank</span>(mean_ToT),
         <span class="dt">Level =</span> <span class="st">&quot;Part&quot;</span>)

D_team_mean &lt;-
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(Team, Condition) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_ToT =</span> <span class="kw">mean</span>(ToT, <span class="dt">na.rm =</span> T),
            <span class="dt">n_Obs =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">Unit =</span> Team) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">percentile =</span> <span class="kw">percent_rank</span>(mean_ToT),
         <span class="dt">Level =</span> <span class="st">&quot;Team&quot;</span>)

D_task_mean &lt;-
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(Task, Condition) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_ToT =</span> <span class="kw">mean</span>(ToT, <span class="dt">na.rm =</span> T),
            <span class="dt">n_Obs =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">Unit =</span> Task) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">percentile =</span> <span class="kw">percent_rank</span>(mean_ToT),
         <span class="dt">Level =</span> <span class="st">&quot;Task&quot;</span>)


<span class="kw">bind_rows</span>(D_team_mean,
          D_part_mean) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> percentile, 
             <span class="dt">y =</span> mean_ToT,
             <span class="dt">col =</span> Level,
             <span class="dt">shape =</span> Level,
             <span class="dt">size =</span> Level)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/CUE8_eda-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(CUE8)</code></pre></div>
<p>It seems there is ample variation in ToT for participants, with mean ToT ranging from below 100 to almost 500 seconds. There is variation in team-wise ToT, too, although less pronounced. This observation is congruent with the <em>law of small numbers</em>, which will be discussed in the following section.</p>
<p>The model is easily specified with the familiar syntax. In fact, it is not even necessary to specify that participants are nested within teams. The only requirement is that participant identifiers are unique across the whole study (not just within a team unit). The model below contains another feature of ths CUE8 study. Participants were tested in one of two conditions: moderated and remote testing sessions. Mixing fixed and random effects, we examine all influences simultaneously.</p>
<p>Note that this treatment is between-subject for participants. There is also just one team that did both conditions. For specifying hierarchical random effects we can use the same syntax as before, <em>if</em> all participants have a unique identifier. If the participant identifier is only unique within a team, it is either to be recoded, e.g. <code>mutate(Part = str_c(Team, Part))</code>, or one uses the nesting operator <code>Part/Team</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(CUE8)

M_<span class="dv">1</span> &lt;-<span class="st"> </span>
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stan_lmer</span>(logToT <span class="op">~</span><span class="st"> </span>Condition <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Part) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Team),
       <span class="dt">data =</span> .)

P_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">posterior</span>(M_<span class="dv">1</span>)

<span class="kw">detach</span>(CUE8)</code></pre></div>
<p>After running the model, we compare the sources of variation. Recall, that LMM assume that the ramdom effects are drawn from a normal distribution and the amount of systematic variation is represented by <span class="math inline">\(\sigma\)</span>. As this is precisely the way, normal distributed errors are represented, we can actually distinguish three levels of variation: participants, team and observations (residuals). The table below tells that the strongest variation is still on observation-level. Almost the same amount of variation is due to teams. And, surprisingly, the variation due to teams is considerably smaller than participant-level variation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(CUE8)
T_sov &lt;-<span class="st"> </span><span class="kw">coef</span>(P_<span class="dv">1</span>, <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;grpef&quot;</span>, <span class="st">&quot;disp&quot;</span>))
T_sov</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">parameter</th>
<th align="left">type</th>
<th align="left">fixef</th>
<th align="left">re_factor</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sigma_resid</td>
<td align="left">disp</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="right">0.611</td>
<td align="right">0.592</td>
<td align="right">0.632</td>
</tr>
<tr class="even">
<td align="left">Sigma[Part:Intercept,(Intercept)]</td>
<td align="left">grpef</td>
<td align="left">Intercept</td>
<td align="left">Part</td>
<td align="right">0.427</td>
<td align="right">0.388</td>
<td align="right">0.468</td>
</tr>
<tr class="odd">
<td align="left">Sigma[Team:Intercept,(Intercept)]</td>
<td align="left">grpef</td>
<td align="left">Intercept</td>
<td align="left">Team</td>
<td align="right">0.589</td>
<td align="right">0.405</td>
<td align="right">0.940</td>
</tr>
</tbody>
</table>
<p>It is hard to deny that, at least for consumer systems, people vary greatly in performance. That is the whole point about universal design. The discordance, between professional teams is concerning. And that arises after controlling for an experimental factor, remote or moderated. By the way, the difference between moderated and remote testing is <span class="math inline">\(0.33 [-0.31, 1.05]_{CI95}\)</span>. The fixed effect is rather weak and highly uncertain.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">T_fixef &lt;-<span class="st"> </span><span class="kw">fixef</span>(P_<span class="dv">1</span>)
T_fixef</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">fixef</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Intercept</td>
<td align="right">4.614</td>
<td align="right">4.093</td>
<td align="right">5.10</td>
</tr>
<tr class="even">
<td align="left">Conditionmoderated</td>
<td align="right">0.331</td>
<td align="right">-0.311</td>
<td align="right">1.05</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(CUE8)</code></pre></div>
</div>
<div id="what-are-random-effects-on-pooling-and-shrinkage" class="section level2">
<h2><span class="header-section-number">6.7</span> What are random effects? On pooling and shrinkage</h2>
<p>At least half a dozen of defintions exist for the term random effect. This is so confusing that some authors refrain to use the term altogether. Here the definition is conceptually based on the idea of a population. Technically, it is compatible with the implementation found in <code>rstanarm</code> and other engines. Unfortunately, the very terms <em>random effect</em> and <em>random factor</em> are highly misleading, as there is nothing more or less random in a random factors as compared to fixed factors. The opposite is the case: as we have seen above, a random effects pulls a variance component from the random term and explains it by assigning coefficients to entities (teams or users). The best advice is to not contemplate over what makes a factor random. It is just a name and because random factors are so amazingly useful, they should be called fonzy factors, instead.</p>
<p>When a data set contains a factor that we may wish to add to the model, the question is: fixed effect or random effect? Above, I have introduced the heuristic of populations. If one can conceive tasks, designs, or whatever set of items, as a population, there is clumping to some degree, but also variation. The more clumping there is, observing some members gives a more or less good guess for unobserved members. In such a case, the predictor is introduced as a fonzy factor. Now, it is in order, to more formally conceive when a set of things is a population.</p>
<p>Obviously, we would never speak of a population, when the objects of interest are from different classes. Entities gathering on super market parking lots, persons, cars, baskets and and dropped brochures, we would never see as a population. People, we would generally see as a population, as long as what we want to observe is somewhat homogenous. When the question is, how fast persons can do a 2000 meter run at the olympic games, we would certainly want one population per discipline (swimming, running, etc). Why is that so? It is because we expect members of a population to have some similarity, in other words: if you have observed how some members of the population behave, you get an idea about the unobserved.</p>
<p>Reconsider the Bayesian principle of prior knowledge by an experiment of thought: Consider, a UX expert with experience in e-commerce is asked to estimate how long it takes users to do the checkout, <em>without being shown the system</em>. The expert will probably hesitate briefly, and then come up with an estimate of, let’s say, 45 seconds. Without any data, the expert made some reasonable assumptions, e.g. that a disciplined design process has been followed, and then relies on experience. The experts personal experience has formed prior to the study by observing many other cases. Now, we confront the expert with an even more bizzare situation: guess the time-on-task for an unknown task with an unseen system of unknown type! The expert will probably refuse to given an answer, arguing that some systems have tasks in the millisecond range (e.g. starting a stopwatch), whereas other processes easily run for hours or days (e.g. doing data exploration). This is agreeable, and we provide the expert with average ToT of four other tasks within the same system:</p>
<p><span class="math inline">\(ToT_{1-4} = {23, 45, 66, 54}\)</span></p>
<p>Now, the expert is confident that ToT be around 50 seconds and that is probably a good guess. What has happened is that prior belief about the unkown task parameter has been formed not externally, but <em>by data</em> as it arrived. The likely value of one unit has been learned from the other units and this appears pretty reasonable. The same principle applies when removing outliers. When staring at a boxplot or scatterplot the mind of the observer forms a gestalt that covers the salient features of data, for example: almost all points are located in the range 100 - 500. Once this pattern has formed, deviant points stand out.</p>
<p>However, the salience of the gestalt may vary. Consider a situation where ToT has been measured by the same procedure, but using five different stop watches. Stop watches are so incredibly accurate that if you know one measure, you basically know them all. What many researcher do with repeated measures data is average over the repetitions. This is the one extreme called <em>total pooling</em>. In the stopwatch case the average across the five measures would be so highly representative, that total pooling is a reasonable thing to do.</p>
<p>In other cases, the levels of a factor are more or less independent, for example tasks in a complex system, where procedure duration ranges from seconds to hours. Guessing the duration of one task from a set of others is highly susceptible and the average duration across tasks is not representative at all. The best choice then is to see tasks as factor levels, that are independent. This extreme of <em>no pooling</em> is exactly represented by fixed effects factors as they have been introduced in @ref(linear_models).</p>
<p>Random effects sit right between these two extremes of no and partial pooling and implement <em>partial pooling</em>: the more the group mean is representative for the units of the group, the more it is taken into account. The best thing about partial pooling is that, unlike real priors, there is not even the need to determine the amount of pooling in advance. The variation of entities has been observed. The stronger the enities vary, the less can be learned from the group level. The variation is precisely the group-level standard deviation of the random effect. So, we can think of random factors as factors where there is a certain amount of cross-talk between levels. The random effect estimate then draws on two sources of evidence: all data from the over-arching population and data that belongs just to this one entity. As that is the case, the exploratory analysis of individual performance in SOV does not resemble a true random effect, as group means were calculated independently.</p>
<p>How are random effects implemented to draw on both sources? Obviously, the procedure must be more refined than just putting dummy variables in a likelihood formula. In the Bayesian framework, a remarkably simple trick suffices, and it is a familiar one. By the concept of prior distributions, we already know a way to restrict the range of an effect, based on prior knowledge. For example, intelligence test results have the prior distribution <span class="math inline">\(IQ ~ N(100, 15)\)</span>, just because they have been empirically calibrated this way. In most other cases, we do have rough ideas about the expected magnitude and range in the population, say: healthy human adults will finish a 2000m run in the range of 5-12 minutes.</p>
<p>As prior knowledge is external to the data, it often lacks systematic evidence, with the exception of a meta analysis. This is why we tend to use weakly informative priors. Like priors, random effects take into account knowledge external to the entity under question. But, they draw this knowledge from the data, which is more convincing, after all. The basic trick to establish the cross-talk between random factor levels, is to <em>simultaneously estimate factor levels and random factor variation</em>. This has several consequences:</p>
<p>All random effects get a more or less subtle trend towards the population mean. As a side effect, the random factor variance usually is a smaller than variance between fixed factors, or naive group means. This effect is called <em>shrinkage</em>. When the random factor variation is small, extreme factor levels are pulled stronger towards the population mean, resulting in stronger shrinkage. Or vice versa: When random variation is large, the factor levels stand more on their own.</p>
<p>The random factor variation is an estimate and as such is certain only to a degree. As we have seen in <a href="multilevel-models.html#crossover">6.4</a>, the more levels a random factor comprises, the more precise is the estimate of random factor variation. The strongest shrinkage occurs with few observations per factor levels and highly certain random factor variation.</p>
<p>Previously, I have stressed how important repeated measures design is, and the number of observations per entity plays a role, too. The more observations there are, the less is the group mean over-ruled by the population mean. Less shrinkage occurs. This is why mixed-effects models gracefully deal with imbalanced designs. Groups with more observations are just gradually more self-determined. Taking this to the opposite extreme: when a factor level contains no data at all, it will just be replaced by the population mean. This principle offers a very elegant solution to the problem of missing data. If you know nothing about a person, the best guess is the population mean.</p>
<p>Under the perspective of populations as a more or less similar set of entities, these principles seem to make sense. Within this framework, we can even define what fixed effects are:</p>
<blockquote>
<p>a fixed effect is a factor where levels are regarded so unsimilar, that the factor-level distribution can be practically considered infinite.</p>
</blockquote>
<p>We routinely approximate such a situation when using non-informative prior distributions, like <span class="math inline">\(\beta_0 ~ N(0, 10000)\)</span>. In the extreme case, a uniform distribution with an infinite upper boundary truly has an infinite variance: <span class="math inline">\(\beta_0 ~ U(0, \infty)\)</span>. A finite population mean doesn’t even exist with such a distribution.</p>
<p>So, when a design researcher has observed that with design A, ToT is approximately distributed as <span class="math inline">\(ToT_A ~ N(120, 40)\)</span>, is it a realistic to assume that design B has ToT in the range of several hours? Would a cognitive psychologist see it equally likely that the difference in reaction time on two primitive tasks is 200ms or 2h. Probably not. Still, using fixed effects for factors with very few levels is a justifyable approximation. First of all, at any time can priors be used to factor in reasonable assumptions about the range. Second, with very few estimates, the random factor variation cannot be estimated with any useful certainty. Very small shrinkage would occur and the results would practically not differ.</p>
<p>The CUE8 study makes a case for seeing shrinkage in action: Teams of researchers were asked to conduct a performance evaluation on a website. Tasks and website were the same, but the teams followed their own routines. Some teams tested a few handful of participants, whereas others tested dozens remotely. Teams, as another non-human population (sic!) differ vastly in the number of observations they collected. We can expect differences in shrinkage. To see the effect, we compare the team-level group means as fixed factor versus random factor. All teams have enough participants tested to estimate their mean with some certainty. At the same time, the group sizes varies so dramatically that we should see clear differences in tendency towards the mean.</p>
<p>We estimate two models, a random effects model and a fixed effects model. For the RE model, the absolute group means are calculated on the posterior. Figure XY shows the comparison of FE and RE estimates.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(CUE8)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_<span class="dv">2</span> &lt;-<span class="st"> </span>
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stan_glm</span>(logToT <span class="op">~</span><span class="st"> </span>Team <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> .)

M_<span class="dv">3</span> &lt;-<span class="st"> </span>
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stan_glmer</span>(logToT <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Team), <span class="dt">data =</span> .)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">P_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">posterior</span>(M_<span class="dv">2</span>, <span class="dt">type =</span> <span class="st">&quot;fixef&quot;</span>)
P_3_fixef &lt;-<span class="st">  </span><span class="kw">posterior</span>(M_<span class="dv">3</span>, <span class="dt">type =</span> <span class="st">&quot;fixef&quot;</span>)
P_3_ranef &lt;-<span class="st">  </span><span class="kw">posterior</span>(M_<span class="dv">3</span>, <span class="dt">type =</span> <span class="st">&quot;ranef&quot;</span>)

## Creating a derived posterior with absolute team-level random effects
P_3_abs &lt;-
<span class="st">  </span><span class="kw">left_join</span>(P_3_ranef, P_3_fixef,
    <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;chain&quot;</span>, <span class="st">&quot;iter&quot;</span>, <span class="st">&quot;fixef&quot;</span>),
    <span class="dt">suffix =</span> <span class="kw">c</span>(<span class="st">&quot;&quot;</span>,<span class="st">&quot;_fixef&quot;</span>))

P_3_abs<span class="op">$</span>value &lt;-<span class="st">  </span>P_3_abs<span class="op">$</span>value <span class="op">+</span><span class="st"> </span>P_3_abs<span class="op">$</span>value_fixef


T_shrinkage &lt;-<span class="st"> </span>
<span class="st">  </span>D_cue8 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(Team) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">N =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">fixef =</span> <span class="kw">fixef</span>(P_<span class="dv">2</span>)<span class="op">$</span>center,
         <span class="dt">ranef =</span> <span class="kw">ranef</span>(P_3_abs)<span class="op">$</span>center,
         <span class="dt">diff =</span> fixef <span class="op">-</span><span class="st"> </span>ranef) 


sd_fixef &lt;-<span class="st"> </span><span class="kw">sd</span>(T_shrinkage<span class="op">$</span>fixef)
sd_ranef &lt;-<span class="st"> </span><span class="kw">sd</span>(T_shrinkage<span class="op">$</span>ranef)


T_shrinkage <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Team, <span class="dt">y =</span> fixef, <span class="dt">size =</span> N, <span class="dt">col =</span> <span class="st">&quot;fixef&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ranef, <span class="dt">col =</span> <span class="st">&quot;ranef&quot;</span>), <span class="dt">alpha =</span> .<span class="dv">5</span>)</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/CUE8_fe_vs_re-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(CUE8)</code></pre></div>
<p>Team H is far off the population average, but almost no shrinkage occurs due to the large number of observations. Again, no shrinkage occurs for Team L, as it is close to the population mean, and has more than enough data to speak for itself. Team B with the fewest observation (a genereous <span class="math inline">\(N = 45\)</span>, still), gets noticable shrinkage, although it is quite close to the population mean. Overall, the pattern resembles the above properties of random effects: groups that are far off the population mean and have comparably small sample size get a shrinkage correction. In the case of CUE8, these correction are overall negligible, which is due to the fact that all teams gathered ample data. Recall the SOV simulation above, where the set of tasks every user did was beyond control of the researcher. In situations with quite heterogeneous amount of missing data per participant, shrinkage is more pronounced and more information is drawn from the population mean.</p>
<p>At the same time, shrinkage adjusts the estimates for variation, with <span class="math inline">\(sd_{RE} = 0.583 &lt; sd_{FE} = 0.588\)</span>. The random effects estimate is an unbiased estimate for the population variance, whereas fixed effects variation would be overestimating. [REF]</p>
<p>Now that random effects have been de-mystified as effects with partial pooling, where the amount of pooling is a consequence of observed data, we can move on to applications. The variance in the population is an indicator for heterogeneity of participants (or any non-human population) and random effects variation is an accurate estimator for that. For designers, it is vital to understand how varied performance with a system is. Furthermore, as we will see in the next section, with slope random effects we can even estimate the variation of how users respond to different design conditions. When comparing two designs A and B, that enables the researcher to assess in how much a desig is uniformly better, a desireable property of universal designs. There also are a useful applications for the random effects, i.e., the individual levels. In some applications the crucial issue is to get good estimates of individual performance, which falls into the domain of psychometrics.</p>
</div>
<div id="slope_RE" class="section level2">
<h2><span class="header-section-number">6.8</span> Variance in variation: slope random effects [TBC]</h2>
<p>So far, we have dealt with random effects that capture the gross differences of entities: individuals differ in how quick they work, task differ in length and test items in difficulty. We introduced these random effects as conditional effects like: “the intercept depends on what person you are looking at”. Whereas in the beginning of the chapter I emphasized the necessity to examine within-person processes in within-subject designs, we never went beyond conditional statements regarding the intercept effect. In contrast consider the A/B testing case. Being more efficient with design B compared to A is the primary question and that we can straight-forwardly put into a conditional statement: “by how much B is more efficient than A depends on the person”.</p>
<p>Let’s first exlore graphically what this means. Assume that we had tested only five participants with one task each. The CGM model with participant-level random effect takes the following form:</p>
<p><span class="math display">\[
\mu_i = \beta_0 + \beta_{0p} + x_1\beta_1\\
\beta_{0p} \sim N(0,\sigma_{0p})
\]</span> The figure below illustrates the model on a sample of five participants. As the effect is the same, we see five parallel lines. While the height where a line starts differs between users, the all benefit to the precisely same amount from design B. Is that realistic? If we expect that differential design effects exist, it is not. There can be plenty of reasons why two users differ in how much the benefit from a certain design. For example, the BrowsingAB case features a strong interaction effect on age. When thinking of random effects, it helps to imagine the situation´where an influencing factor exists, but was not recorded. The inter-individual variance will remain, and the participant identifier is the only predictor at hand.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">n_Part =</span> <span class="dv">5</span>,
                <span class="dt">beta_0P =</span> <span class="kw">rnorm</span>(n_Part,<span class="dv">0</span>, sigma_0P),
                <span class="dt">sigma_0P =</span> <span class="dv">20</span>,
                <span class="dt">beta_1P =</span> <span class="kw">rnorm</span>(n_Part,<span class="dv">0</span>, sigma_1P),
                <span class="dt">sigma_1P =</span> <span class="dv">0</span>,
                <span class="dt">sigma_eps =</span> <span class="dv">0</span>) {
  Part =<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">Part =</span> <span class="dv">1</span><span class="op">:</span>n_Part, 
                     <span class="dt">beta_0P =</span> beta_0P, 
                     <span class="dt">beta_1P =</span> beta_1P)
  Design =<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">Design =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>),
                       <span class="dt">beta_0 =</span> <span class="dv">120</span>,
                       <span class="dt">beta_1 =</span> <span class="op">-</span><span class="dv">30</span>)
  mascutils<span class="op">::</span><span class="kw">expand_grid</span>(<span class="dt">Part =</span> Part<span class="op">$</span>Part, <span class="dt">Design =</span> Design<span class="op">$</span>Design) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">left_join</span>(Part) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">left_join</span>(Design) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">mu =</span> beta_<span class="dv">0</span> <span class="op">+</span><span class="st"> </span>beta_0P <span class="op">+</span><span class="st"> </span>(beta_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>beta_1P) <span class="op">*</span><span class="st"> </span>(Design <span class="op">==</span><span class="st"> &quot;B&quot;</span>),
           <span class="dt">ToT =</span> <span class="kw">rnorm</span>(<span class="kw">nrow</span>(.), mu, <span class="dv">0</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">as_tbl_obs</span>()
}

<span class="kw">sim</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Design, 
             <span class="dt">y =</span> ToT,
             <span class="dt">group =</span> Part)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>()</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>A more realistic figure of the effects is the spaghetti plot below. All participants improve with design B, but to rather different degrees. The lines have different starting points, and they differ in slopes. This is called a <em>slope random effect</em>. Similar to intercept random effects, slope random effects are factors that represent individual deviations from the population-level effect.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sim</span>(<span class="dt">sigma_1P =</span> <span class="dv">15</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Design, 
             <span class="dt">y =</span> ToT,
             <span class="dt">group =</span> Part)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>()</code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>For the design effect in BrowsingAB, a model with intercept and slope random effects is formally specified as:</p>
<p><span class="math display">\[
\mu_i = \beta_0 + \beta_{0p} + x_1\beta_1 + x_{1}\beta_{1p}\\
\beta_{0p} \sim N(0,\sigma_{0p})\\
\beta_{1p} \sim N(0,\sigma_{1P})
\]</span></p>
<p>Previously, we have seen that repeated measures are the key to pull a random effect out of the residual term. The same holds for slope random effects. For estimating individual slopes, the same participant (or any non-human entity) must encounter multiple conditions. For demonstration of slope random effects, we examine another instantiation of the BrowsingAB data set <code>BAB5</code>, which differs from <code>BAB1</code> in two aspects: all participants encounter both designs (within-entity design) and ToT was measured on five given tasks (repeated measures). We use the simulation function as provided by the BrowsingAB case environment. As always, we start with some exploratory analysis.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(BrowsingAB)</code></pre></div>
<p>The spaghetti plot (the pasta is dry, not cooked) is excellent for visualizing participant-level effects. For the BAB5 data set the following figure shows the individual design effects. While on average design B is favored, there is a wild bunch of slopes. That should not surprise us, as in the previous chapter we discovered a strong interaction effect by age. Here we ignore this predictor (or pretending not to have recorded it) and exclusively work with the participant factor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">G_slope_RE_<span class="dv">1</span> &lt;-
<span class="st">  </span>BAB5 <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(Part, Design) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">ToT =</span> <span class="kw">mean</span>(ToT)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Design, 
              <span class="dt">y =</span> ToT)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">color =</span> <span class="st">&quot;participant effects&quot;</span>, <span class="dt">group =</span> Part), <span class="dt">alpha =</span> .<span class="dv">7</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data =</span> <span class="kw">group_by</span>(BAB5, Design) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">ToT =</span> <span class="kw">mean</span>(ToT)), 
            <span class="kw">aes</span>(<span class="dt">X =</span> Design, <span class="dt">y =</span> ToT, <span class="dt">group =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;population effect&quot;</span>), <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">color =</span> <span class="ot">NULL</span>)

G_slope_RE_<span class="dv">1</span></code></pre></div>
<p><img src="Linear_mixed-effects_models_files/figure-html/BAB_RE_age-1.png" width="672" /> The R formula for slope random effects follows the same principles as before. For the present case it reads as “the intercept and design effect are <em>conditional</em> on participants”: <code>(1 + Design|Part)</code>. We estimate the model using the rstanarm engine and use the usual commands to extract population-level estimates and random effect variation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_Des_ME &lt;-<span class="st"> </span><span class="kw">stan_glmer</span>(ToT <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Design <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Design<span class="op">|</span>Part),
                       <span class="dt">data =</span> BAB5)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">P_Des_ME &lt;-<span class="st"> </span><span class="kw">posterior</span>(M_Des_ME)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(BrowsingAB)</code></pre></div>
<p>Mind to always put complex random effects into brackets, as the <code>+</code> operator binds very strongly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(BrowsingAB)

M_slope_<span class="dv">1</span> &lt;-
<span class="st">  </span><span class="kw">stan_glmer</span>(ToT <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Design <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Design<span class="op">|</span>Part),
             <span class="dt">data =</span> BAB5)

P_slope_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">posterior</span>(M_slope_<span class="dv">1</span>)

<span class="kw">detach</span>(BrowsingAB)</code></pre></div>
<p>The random factor variation is extracted from the posterior distribution using the <code>grpef</code> command. The coefficients are standard deviations of the two random factors INtercept and DesignB. The results confirm the earlier fixed effects analysis on the data set: users experience very different advantages of Design B. The variation of the difference is almost as pronounced as the variation on Design A (Intercept), alone. The standard deviation has the same magnitude as the group level effect, hence some users are likely to experience a disadvantage, even. That matches the earlier results, where design B caused problems for elderly users. In fact, we can phrase the slope random effect in much the same way as interaction effect <code>age:Design</code> in @ref(differential_design_effects), namely as a conditional statement of the form:</p>
<blockquote>
<p>the effect of Design depends on the participant.</p>
</blockquote>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(BrowsingAB)

P_slope_<span class="dv">1</span> <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(fixef <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Intercept&quot;</span>, <span class="st">&quot;DesignB&quot;</span>),
         type <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;grpef&quot;</span>, <span class="st">&quot;fixef&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(re_factor, fixef) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">center =</span> <span class="kw">median</span>(value, <span class="dt">na.rm =</span> T),
            <span class="dt">lower =</span> <span class="kw">quantile</span>(value, .<span class="dv">05</span>, <span class="dt">na.rm =</span> T),
            <span class="dt">upper =</span> <span class="kw">quantile</span>(value, .<span class="dv">95</span>, <span class="dt">na.rm =</span> T)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">re_factor</th>
<th align="left">fixef</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Part</td>
<td align="left">DesignB</td>
<td align="right">18.9</td>
<td align="right">9.63</td>
<td align="right">33.86</td>
</tr>
<tr class="even">
<td align="left">Part</td>
<td align="left">Intercept</td>
<td align="right">17.6</td>
<td align="right">10.48</td>
<td align="right">26.45</td>
</tr>
<tr class="odd">
<td align="left">NA</td>
<td align="left">DesignB</td>
<td align="right">-20.6</td>
<td align="right">-32.36</td>
<td align="right">-8.93</td>
</tr>
<tr class="even">
<td align="left">NA</td>
<td align="left">Intercept</td>
<td align="right">99.5</td>
<td align="right">91.27</td>
<td align="right">108.17</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(BrowsingAB)</code></pre></div>
<p>Intercept random effects capture gross variations between users. Independent of designs, tasks or situation, some users are assumed to always be faster, more accurate or pleased. That is certainly better than sticking with the image of the average user, but it remains static. With slope random effects can we render <em>individual differences in the process</em>. How differently do individual users react when proceeding from design A to B? That is a completely different question than the average difference between designs. Review the spaghetti plot @ref(fig:BAB_RE_age) once again. Adding a slope random effect to the model really means that the effect is estimated as many times as there are participants in the sample (run <code>ranef(M_slope_1)</code> to see it). And these coefficients tell a story about <em>generalizeability</em>. The more the random effects are dispersed, the less typical is the average (the fixed effect). When you are doing a user study for an e-commerce company, it may be sufficient to just tell the average figure (and maybe even a good idea as to not overwhelm the mind of your manager). However, when doing design experiments for the purpose of finding more generally applicable rules for good design, generalizeability matters. In fact, with a CGM that compares to independent groups, you cannot prove that the hypothesized process (e.g., larger fonts are better to read) holds for everyone.</p>
<p>Proving that an effect is practically universal across participants is possible with slope random effects, but requires rendering individual trajectories. That is only possible, if the study assesses the conditions in question for every participant. This is called a within-subject design. Anyone who as trustingly made generalizing conclusions on the basis of a between-subject manipulations, should feel deeply troubled. Can we actually be sure that:</p>
<ul>
<li>everyone experiences the uncanny valley effect, when viewing robot faces?</li>
<li>everyone’s alertness when sleepy benefits from noise?</li>
<li>every nurse makes fewer errors with a third millenium infusion pump design?</li>
</ul>
<p>Even researchers doing plain user studies cannot refrain from the issue completely. When the system is safety critical, it matters that a particular design is an universal improvement over the other. Who ever operates it, errors must occur less frequently. In the next chapter, we will encounter such a study, where a novel infusion pump interface was compared with a legacy design. Furthermore, we examined how performance with both devices changed with practice. As the experiment was fully within-subject it is open to investigate generalizeability on both issues:</p>
<ul>
<li>do all participants benefit from the modern design?</li>
<li>do all participants learn over the course of the experiment?</li>
</ul>
<p>As we will see in <a href="GLM.html#GLM">7</a>, most of the recorded performance measures do not comply with the assumptions of linear models and only the measure of perceived workload seems amenable. We construct a model that captures the two main factors (design and session) with a possible interaction effect. Intercept and slope random effects are added for participants and tasks:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(IPump)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">M_wkld &lt;-<span class="st">   </span>
<span class="st">  </span>D_pumps <span class="op">%&gt;%</span><span class="st">  </span>
<span class="st">  </span><span class="kw">stan_glmer</span>(workload <span class="op">~</span><span class="st"> </span>Design<span class="op">*</span>Session <span class="op">+</span><span class="st"> </span>(Design<span class="op">*</span>Session<span class="op">|</span>Part) <span class="op">+</span><span class="st"> </span>(Design<span class="op">*</span>Session<span class="op">|</span>Task),
                     <span class="dt">data =</span> .)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fixef</span>(M_wkld)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">fixef</th>
<th align="right">center</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Intercept</td>
<td align="right">21.00</td>
<td align="right">14.13</td>
<td align="right">28.20</td>
</tr>
<tr class="even">
<td align="left">DesignNovel</td>
<td align="right">-8.03</td>
<td align="right">-12.30</td>
<td align="right">-3.78</td>
</tr>
<tr class="odd">
<td align="left">Session2-1</td>
<td align="right">-8.14</td>
<td align="right">-12.80</td>
<td align="right">-3.20</td>
</tr>
<tr class="even">
<td align="left">Session3-2</td>
<td align="right">-5.69</td>
<td align="right">-10.32</td>
<td align="right">-1.14</td>
</tr>
<tr class="odd">
<td align="left">DesignNovel:Session2-1</td>
<td align="right">2.20</td>
<td align="right">-3.64</td>
<td align="right">7.96</td>
</tr>
<tr class="even">
<td align="left">DesignNovel:Session3-2</td>
<td align="right">1.62</td>
<td align="right">-4.50</td>
<td align="right">7.59</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#grpef(M_wkld) </span><span class="al">FIXME</span><span class="co"> bayr</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">posterior</span>(M_wkld) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(type <span class="op">==</span><span class="st"> &quot;grpef&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(parameter) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">median =</span> <span class="kw">median</span>(value)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(median)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">parameter</th>
<th align="right">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Sigma[Part:DesignNovel,DesignNovel]</td>
<td align="right">6.52</td>
</tr>
<tr class="even">
<td align="left">Sigma[Part:DesignNovel:Session2-1,DesignNovel:Session2-1]</td>
<td align="right">3.41</td>
</tr>
<tr class="odd">
<td align="left">Sigma[Part:DesignNovel:Session3-2,DesignNovel:Session3-2]</td>
<td align="right">4.07</td>
</tr>
<tr class="even">
<td align="left">Sigma[Part:Intercept,(Intercept)]</td>
<td align="right">12.38</td>
</tr>
<tr class="odd">
<td align="left">Sigma[Part:Session2-1,Session2-1]</td>
<td align="right">4.79</td>
</tr>
<tr class="even">
<td align="left">Sigma[Part:Session3-2,Session3-2]</td>
<td align="right">3.83</td>
</tr>
<tr class="odd">
<td align="left">Sigma[Task:DesignNovel,DesignNovel]</td>
<td align="right">3.22</td>
</tr>
<tr class="even">
<td align="left">Sigma[Task:DesignNovel:Session2-1,DesignNovel:Session2-1]</td>
<td align="right">2.37</td>
</tr>
<tr class="odd">
<td align="left">Sigma[Task:DesignNovel:Session3-2,DesignNovel:Session3-2]</td>
<td align="right">2.62</td>
</tr>
<tr class="even">
<td align="left">Sigma[Task:Intercept,(Intercept)]</td>
<td align="right">6.91</td>
</tr>
<tr class="odd">
<td align="left">Sigma[Task:Session2-1,Session2-1]</td>
<td align="right">2.81</td>
</tr>
<tr class="even">
<td align="left">Sigma[Task:Session3-2,Session3-2]</td>
<td align="right">2.49</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">detach</span>(IPump)</code></pre></div>
<div id="section" class="section level4">
<h4><span class="header-section-number">6.8.0.1</span> </h4>
</div>
<div id="exercises-6" class="section level4">
<h4><span class="header-section-number">6.8.0.2</span> Exercises</h4>
<ol style="list-style-type: decimal">
<li>Review the scientific literature in your field. Find examples of design experiments where general conclusions were drawn from between-subject predictors. If that was easy, visit one of the leading social psychology journals and repeat.</li>
</ol>
</div>
</div>
<div id="re_correlations" class="section level2">
<h2><span class="header-section-number">6.9</span> Growing with random effects correlations [TBD]</h2>
<p>Here we finally resolve the Typing paradox and encounter another immensely useful element in random effect modelling. Let’s take another good look at the Figure X [Average? Neverage. Last one].</p>
</div>
<div id="advanced-tricks" class="section level2">
<h2><span class="header-section-number">6.10</span> Advanced tricks</h2>
<ul>
<li>non-compliant test users in CUE8</li>
<li>handling missing values by priors</li>
</ul>
</div>
<div id="exercises-7" class="section level2">
<h2><span class="header-section-number">6.11</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li>In the Egan study, cross-classified random effects capture the encounter of samples. Actually, we have not even taken this to an extreme, as the original study also measured mental workload with a scale of four items. Create and run a model that captures all samples, including the scale items. Interpret the results.</li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>Egan, D. Individual differences in human-computer interaction. In M. Helander, ed., Handbook of Human Computer interaction. Elsevier Science Publishers, Amsterdam, The Netherlands, 1988, 543–568.<a href="multilevel-models.html#fnref2">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="GLM.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
